# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("public") {
  sources = [
    "config.cc",
    "config.h",
    "constants.cc",
    "constants.h",
    "database_client.cc",
    "database_client.h",
    "features.cc",
    "features.h",
    "field_trial_register.h",
    "input_context.cc",
    "input_context.h",
    "input_delegate.cc",
    "input_delegate.h",
    "local_state_helper.h",
    "model_provider.cc",
    "model_provider.h",
    "prediction_options.cc",
    "prediction_options.h",
    "result.cc",
    "result.h",
    "segment_selection_result.cc",
    "segment_selection_result.h",
    "segmentation_platform_service.cc",
    "segmentation_platform_service.h",
    "service_proxy.cc",
    "service_proxy.h",
    "trigger.h",
    "types/processed_value.cc",
    "types/processed_value.h",
  ]

  public_deps = [ "//components/segmentation_platform/public/proto" ]

  deps = [
    "//base",
    "//base:i18n",
    "//components/keyed_service/core",
    "//components/segmentation_platform/embedder/home_modules:constants",
    "//services/metrics/public/cpp:metrics_cpp",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true

  # IMPORTANT NOTE: When adding new tests, also remember to update the list of
  # tests in //components/segmentation_platform/components_unittests.filter
  sources = []

  deps = [
    ":public",
    "//testing/gtest",
  ]
}

source_set("test_support") {
  testonly = true

  sources = [
    "testing/mock_database_client.h",
    "testing/mock_device_switcher_result_dispatcher.h",
    "testing/mock_field_trial_register.h",
    "testing/mock_segmentation_platform_service.h",
  ]

  deps = [
    ":public",
    "//base",
    "//components/segmentation_platform/embedder/default_model",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
