// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=3211ebbce37fece5937eeb3c577eba91fe1e9f1f$
//

#include "libcef_dll/cpptoc/vimbrowser_element_activation_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

#if CEF_API_ADDED(CEF_EXPERIMENTAL)

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK vimbrowser_element_activation_callback_on_complete(struct _cef_vimbrowser_element_activation_callback_t* self, int result, int match_count) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefVimbrowserElementActivationCallbackCppToC::Get(self)->OnComplete(
      result,
      match_count);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefVimbrowserElementActivationCallbackCppToC::CefVimbrowserElementActivationCallbackCppToC() {
  GetStruct()->on_complete = vimbrowser_element_activation_callback_on_complete;
}

// DESTRUCTOR - Do not edit by hand.

CefVimbrowserElementActivationCallbackCppToC::~CefVimbrowserElementActivationCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template<> CefRefPtr<CefVimbrowserElementActivationCallback> CefCppToCRefCounted<CefVimbrowserElementActivationCallbackCppToC, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_t>::UnwrapDerived(CefWrapperType type, cef_vimbrowser_element_activation_callback_t* s) {
  CHECK(false) << __func__ << " called with unexpected class type " << type;
  return nullptr;
}

template<> CefWrapperType CefCppToCRefCounted<CefVimbrowserElementActivationCallbackCppToC, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_t>::kWrapperType = WT_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK;

#endif  // CEF_API_ADDED(CEF_EXPERIMENTAL)
