// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e3190260a356c5383eddc1116039a55bbf67cb83$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/cef_browser.h"
#include "include/capi/cef_browser_capi.h"
#include "include/cef_client.h"
#include "include/capi/cef_client_capi.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

#if CEF_API_ADDED(CEF_EXPERIMENTAL)

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefVimbrowserElementActivationCallbackCppToC
    : public CefCppToCRefCounted<CefVimbrowserElementActivationCallbackCppToC, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_t> {
 public:
  CefVimbrowserElementActivationCallbackCppToC();
  virtual ~CefVimbrowserElementActivationCallbackCppToC();
};

constexpr auto CefVimbrowserElementActivationCallbackCppToC_Wrap = CefVimbrowserElementActivationCallbackCppToC::Wrap;
constexpr auto CefVimbrowserElementActivationCallbackCppToC_Unwrap = CefVimbrowserElementActivationCallbackCppToC::Unwrap;

#endif  // CEF_API_ADDED(CEF_EXPERIMENTAL)

#endif  // CEF_LIBCEF_DLL_CPPTOC_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CPPTOC_H_
