# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chromeos/args.gni")

source_set("smart_card") {
  public_deps = [ "//chrome/browser:browser_public_dependencies" ]
  # TODO(crbug.com/40247152): Add chrome_smart_card_delegate.* for Win/Mac/Linux
  # and move smart_card_* out of the is_chromeos guard.
}
