# Copyright 2019 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
group("password_manager") {
  public_deps = [
    ":factory",
    ":public",
  ]
}

source_set("factory") {
  public_deps = [ ":public" ]
}

source_set("public") {
  deps = [
    "//base",
    "//components/password_manager/core/browser",
  ]

  public_deps = [ "//url" ]

  sources = [ "touch_to_fill_view.h" ]
}
