// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/sync/prefs/chrome_syncable_prefs_database.h"

#include <string_view>

#include "base/containers/fixed_flat_map.h"
#include "build/build_config.h"
#include "chrome/browser/accessibility/tree_fixing/pref_names.h"
#include "chrome/browser/glic/glic_pref_names.h"
#include "chrome/browser/subscription_eligibility/subscription_eligibility_prefs.h"
#include "chrome/browser/ui/read_anything/read_anything_prefs.h"
#include "chrome/browser/ui/toolbar/toolbar_pref_names.h"
#include "chrome/common/pref_names.h"
#include "components/language/core/browser/pref_names.h"
#include "components/live_caption/pref_names.h"
#include "components/performance_manager/public/user_tuning/prefs.h"
#include "components/privacy_sandbox/privacy_sandbox_prefs.h"
#include "components/sync/base/data_type.h"
#include "components/sync_preferences/syncable_prefs_database.h"


#if BUILDFLAG(ENABLE_EXTENSIONS_CORE)
#include "components/supervised_user/core/common/pref_names.h"
#include "extensions/browser/pref_names.h"  // nogncheck
#endif

namespace browser_sync {
namespace {
// Not an enum class to ease cast to int.
namespace syncable_prefs_ids {
// These values are persisted to logs. Entries should not be renumbered and
// numeric values should never be reused. When adding a new entry, append the
// enumerator to the end and add it to the `SyncablePref` enum in
// tools/metrics/histograms/metadata/sync/enums.xml. When removing an unused
// enumerator, comment it out here, making it clear the value was previously
// used, and add "(obsolete)" to the corresponding entry in enums.xml.
// LINT.IfChange(ChromeSyncablePref)
enum {
  // Starts with 100000 to avoid clash with prefs listed in
  // common_syncable_prefs_database.cc and
  // ios_chrome_syncable_prefs_database.cc.
  kAppLanguagePromptShown = 100000,
  // kPrefExplicitLanguageAskShown = 100001,  // deprecated
  kContextualSearchEnabled = 100002,
  kContextualSearchWasFullyPrivacyEnabled = 100003,
  kAccessibilityImageLabelsEnabledAndroid = 100004,
  kAccessibilityImageLabelsOnlyOnWifi = 100005,
  kPromptForDownloadAndroid = 100006,
  kAccessibilityReadAnythingFontName = 100007,
  kAccessibilityReadAnythingFontScale = 100008,
  kAccessibilityReadAnythingColorInfo = 100009,
  kAccessibilityReadAnythingLineSpacing = 100010,
  kAccessibilityReadAnythingLetterSpacing = 100011,
  kLensRegionSearchEnabled = 100012,
  kHatsSurveyMetadata = 100013,
  kHomePage = 100014,
  kHomePageIsNewTabPage = 100015,
  kNtpCustomBackgroundDict = 100016,
  kLiveCaptionBubbleExpanded = 100017,
  // kLiveCaptionBubblePinned = 100018,  // deprecated
  kLiveCaptionEnabled = 100019,
  kLiveCaptionLanguageCode = 100020,
  kLiveCaptionMediaFoundationRendererErrorSilenced = 100021,
  kShowHomeButton = 100022,
  kPinnedExtensions = 100023,
  kSupervisedUserApprovedExtensions = 100024,
  // kIsDefaultPageColorsOnHighContrast = 100025, (deprecated)
  kShowFullscreenToolbar = 100026,
  kAllowJavascriptAppleEvents = 100027,
  kRestoreAppsAndPagesPrefName = 100028,
  kAccessibilityAutoclickDelayMs = 100029,
  kAccessibilityAutoclickEventType = 100030,
  kAccessibilityAutoclickMenuPosition = 100031,
  kAccessibilityAutoclickMovementThreshold = 100032,
  kAccessibilityAutoclickRevertToLeftClick = 100033,
  kAccessibilityAutoclickStabilizePosition = 100034,
  // kAccessibilityCursorColor = 100035, // Synced as 100340 now.
  kAccessibilityEnhancedNetworkVoicesInSelectToSpeakAllowed = 100036,
  kAccessibilityFloatingMenuPosition = 100037,
  // kAccessibilityGreyscaleAmount = 100038,  // deprecated
  // kAccessibilityHueRotationAmount = 100039,  // deprecated
  // kAccessibilitySaturationAmount = 100040,  // deprecated
  // kAccessibilityScreenMagnifierCenterFocus = 100041,  // deprecated
  kAccessibilityScreenMagnifierFocusFollowingEnabled = 100042,
  kAccessibilityScreenMagnifierMouseFollowingMode = 100043,
  kAccessibilitySelectToSpeakBackgroundShading = 100044,
  kAccessibilitySelectToSpeakEnhancedNetworkVoices = 100045,
  kAccessibilitySelectToSpeakEnhancedVoiceName = 100046,
  kAccessibilitySelectToSpeakEnhancedVoicesDialogShown = 100047,
  kAccessibilitySelectToSpeakHighlightColor = 100048,
  kAccessibilitySelectToSpeakNavigationControls = 100049,
  kAccessibilitySelectToSpeakVoiceName = 100050,
  kAccessibilitySelectToSpeakVoiceSwitching = 100051,
  kAccessibilitySelectToSpeakWordHighlight = 100052,
  // kAccessibilitySepiaAmount = 100053,  // deprecated
  kAccessibilitySwitchAccessAutoScanEnabled = 100054,
  kAccessibilitySwitchAccessAutoScanKeyboardSpeedMs = 100055,
  kAccessibilitySwitchAccessAutoScanSpeedMs = 100056,
  kAccessibilitySwitchAccessNextDeviceKeyCodes = 100057,
  kAccessibilitySwitchAccessPointScanSpeedDipsPerSecond = 100058,
  kAccessibilitySwitchAccessPreviousDeviceKeyCodes = 100059,
  kAccessibilitySwitchAccessSelectDeviceKeyCodes = 100060,
  kAppNotificationBadgingEnabled = 100061,
  kEnableAutoScreenLock = 100062,
  kEnableStylusTools = 100063,
  kFilesAppFolderShortcuts = 100064,
  kFilesAppTrashEnabled = 100065,
  kFilesAppUIPrefsMigrated = 100066,
  kLaunchPaletteOnEjectEvent = 100067,
  kLauncherContinueSectionHidden = 100068,
  kLauncherFeedbackOnContinueSectionSent = 100069,
  kLauncherResultEverLaunched = 100070,
  kMessageCenterLockScreenMode = 100071,
  kMouseAcceleration = 100072,
  kMouseReverseScroll = 100073,
  kMouseScrollAcceleration = 100074,
  kMouseScrollSensitivity = 100075,
  kMouseSensitivity = 100076,
  kNaturalScroll = 100077,
  kOobeMarketingOptInChoice = 100078,
  kOobeMarketingOptInScreenFinished = 100079,
  kPointingStickAcceleration = 100080,
  kPointingStickSensitivity = 100081,
  kPowerAdaptiveChargingEnabled = 100082,
  kPowerAdaptiveChargingNudgeShown = 100083,
  kPrimaryMouseButtonRight = 100084,
  kPrimaryPointingStickButtonRight = 100085,
  kProjectorAnnotatorLastUsedMarkerColor = 100086,
  kProjectorCreationFlowEnabled = 100087,
  kProjectorCreationFlowLanguage = 100088,
  kProjectorGalleryOnboardingShowCount = 100089,
  kProjectorViewerOnboardingShowCount = 100090,
  kShelfAlignment = 100091,
  kShelfAutoHideBehavior = 100092,
  kSuggestedContentEnabled = 100093,
  kSyncableWallpaperInfo = 100094,
  kTapDraggingEnabled = 100095,
  kTapToClickEnabled = 100096,
  kTouchpadAcceleration = 100097,
  kTouchpadHapticClickSensitivity = 100098,
  kTouchpadHapticFeedback = 100099,
  kTouchpadScrollAcceleration = 100100,
  kTouchpadScrollSensitivity = 100101,
  kTouchpadSensitivity = 100102,
  kXkbAutoRepeatDelay = 100103,
  kXkbAutoRepeatEnabled = 100104,
  kXkbAutoRepeatInterval = 100105,
  kMostRecentConnectTetheringResponderIds = 100106,
  kMostRecentTetherAvailablilityResponderIds = 100107,
  kGuestOsTerminalSettings = 100108,
  kPreferredLanguagesSyncable = 100109,
  kSyncOsDemographicsPrefName = 100110,
  kAppListPreferredOrder = 100111,
  kChromeOSReleaseNotesVersion = 100112,
  kLanguageEnabledImesSyncable = 100113,
  kLanguagePreloadEnginesSyncable = 100114,
  kLanguageRemapAltKeyTo = 100115,
  kLanguageRemapAssistantKeyTo = 100116,
  kLanguageRemapBackspaceKeyTo = 100117,
  kLanguageRemapCapsLockKeyTo = 100118,
  kLanguageRemapControlKeyTo = 100119,
  kLanguageRemapEscapeKeyTo = 100120,
  kLanguageRemapExternalCommandKeyTo = 100121,
  kLanguageRemapExternalMetaKeyTo = 100122,
  kLanguageRemapSearchKeyTo = 100123,
  kMultiProfileNeverShowIntro = 100124,
  kMultiProfileWarningShowDismissed = 100125,
  // kOfficeSetupComplete = 100126, // deprecated
  kResolveTimezoneByGeolocationMethod = 100127,
  kResolveTimezoneByGeolocationMigratedToMethod = 100128,
  kShelfDefaultPinLayoutRolls = 100129,
  kTextToSpeechLangToVoiceName = 100130,
  kTextToSpeechPitch = 100131,
  kTextToSpeechRate = 100132,
  kTextToSpeechVolume = 100133,
  kUse24HourClock = 100134,
  kUserPrintersAllowed = 100135,
  // kProximityAuthIsChromeOSLoginEnabled = 100136, // deprecated with removal
  // of Sign in with Smart Lock
  kUserImageInfo = 100137,
  kGdataDisabled = 100138,
  kGdataCellularDisabled = 100139,
  // kAlternateErrorPagesEnabled = 100140, (deprecated)
  kTabDiscardingExceptions = 100141,
  kAccessibilityImageLabelsEnabled = 100142,
  kAccessibilityImageLabelsOptInAccepted = 100143,
  // kAccessibilityPdfOcrAlwaysActive = 100144,(deprecated)
  // kApplyPageColorsOnlyOnIncreasedContrast = 100145, (no longer synced)
  kDefaultCharset = 100146,
  kDefaultTasksByMimeType = 100147,
  kDefaultTasksBySuffix = 100148,
  kDevToolsSyncPreferences = 100149,
  kDevToolsSyncedPreferencesSyncEnabled = 100150,
  // kDownloadBubbleIphSuppression = 100151, (deprecated)
  kEnableDoNotTrack = 100152,
  kExtensionCommands = 100153,
  kExtensionsUIDeveloperMode = 100154,
  kHttpsOnlyModeEnabled = 100155,
  // IDs 100156 and 100157 were used by removed Live Translate preferences.
  kNetworkEasterEggHighScore = 100158,
  kNetworkPredictionOptions = 100159,
  kNetworkQualities = 100160,
  // kNtpAppPageNames = 100161, (deprecated)
  // kPageColors = 100162, (deprecated)
  kPerformanceTracingEnabled = 100163,
  kPluginsAlwaysOpenPdfExternally = 100164,
  // kPrivacySandboxApisEnabled = 100165, (deprecated)
  kPrivacySandboxRelatedWebsiteSetsEnabled = 100166,
  // kPrivacySandboxManuallyControlled = 100167, (deprecated)
  kPromptForDownload = 100168,
  kProtectedContentDefault = 100169,
  kRestoreOnStartup = 100170,
  kSearchSuggestEnabled = 100171,
  // kSharingVapidKey = 100172, (moved to components)
  kURLsToRestoreOnStartup = 100173,
  kSpellCheckEnable = 100174,
  kProfileContentSettingsExceptionsAntiAbuse = 100175,
  kProfileContentSettingsExceptionsAutomaticDownloads = 100176,
  kProfileContentSettingsExceptionsCookies = 100177,
  kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens = 100178,
  kProfileContentSettingsExceptionsImages = 100179,
  kProfileContentSettingsExceptionsJavascript = 100180,
  kProfileContentSettingsExceptionsLocalFonts = 100181,
  kProfileContentSettingsExceptionsMouselock = 100182,
  kProfileContentSettingsExceptionsPopups = 100183,
  kProfileContentSettingsExceptionsWindowPlacement = 100184,
  kProfileDefaultContentSettingValuesAntiAbuse = 100185,
  kProfileDefaultContentSettingValuesAutomaticDownloads = 100186,
  kProfileDefaultContentSettingValuesCookies = 100187,
  kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens =
      100188,
  kProfileDefaultContentSettingValuesImages = 100189,
  kProfileDefaultContentSettingValuesJavascript = 100190,
  kProfileDefaultContentSettingValuesLocalFonts = 100191,
  kProfileDefaultContentSettingValuesMouselock = 100192,
  kProfileDefaultContentSettingValuesPopups = 100193,
  kProfileDefaultContentSettingValuesWindowPlacement = 100194,
  kWebauthnCablev2Pairings = 100195,
  kDynamicColorColorScheme = 100196,
  kDynamicColorSeedColor = 100197,
  kLongPressDiacritics = 100198,
  // kSidePanelCompanionEntryPinnedToToolbar = 100199, Deprecated 11/2024.
  kAccessibilityColorCorrectionEnabled = 100200,
  kAccessibilityColorVisionCorrectionAmount = 100201,
  kAccessibilityColorVisionCorrectionType = 100202,
  kShowDeskButtonInShelf = 100203,
  kOsDogfoodGroupsSyncPrefName = 100204,
  kProjectorSWAUIPrefsMigrated = 100205,
  // kDesktopToiOSPasswordPromoLastImpressionTimestamp = 100206, (deprecated)
  // kDesktopToiOSPasswordPromoImpressionsCounter = 100207, (deprecated)
  // kDesktopToiOSPasswordPromoOptOut = 100208, (deprecated)
  kDynamicColorUseKMeans = 100209,
  kRemapToRightClickNotificationsRemaining = 100210,
  kSixPackKeyDeleteNotificationsRemaining = 100211,
  kSixPackKeyHomeNotificationsRemaining = 100212,
  kSixPackKeyEndNotificationsRemaining = 100213,
  kSixPackKeyPageUpNotificationsRemaining = 100214,
  kSixPackKeyPageDownNotificationsRemaining = 100215,
  kSixPackKeyInsertNotificationsRemaining = 100216,
  kLiveCaptionMaskOffensiveWords = 100217,
  kTimeOfLastSessionActivation = 100218,
  kBrowserColorScheme = 100219,
  kBrowserColorVariant = 100220,
  kGrayscaleThemeEnabled = 100221,
  kUserColor = 100222,
  kBlockAll3pcToggleEnabled = 100223,
  // kTrackingProtectionLevel = 100224, (deprecated)
  kUserSpeakOnMuteDetectionEnabled = 100225,
  kShouldShowSpeakOnMuteOptInNudge = 100226,
  kSpeakOnMuteOptInNudgeShownCount = 100227,
  kAccessibilityReadAnythingVoiceName = 100228,
  kAccessibilityReadAnythingSpeechRate = 100229,
  kAccessibilityReadAnythingHighlightGranularity = 100230,
  // kAccessibilityReadAnythingHighlightColor = 100231, (deprecated, never used)
  kPinnedActions = 100232,
  kPinnedSearchCompanionMigrationComplete = 100233,
  kTouchpadInternalSettings = 100234,
  kPointingStickInternalSettings = 100235,
  kMouseDefaultSettings = 100236,
  kKeyboardDefaultChromeOSSettings = 100237,
  kKeyboardDefaultNonChromeOSSettings = 100238,
  kTouchpadDefaultSettings = 100239,
  kFocusModeDoNotDisturb = 100240,
  kFocusModeSessionDuration = 100241,
  kReadAloudVoiceSettings = 100242,
  kReadAloudSpeed = 100243,
  kReadAloudHighlightingEnabled = 100244,
  kHttpsFirstModeIncognito = 100245,
  // kAccessibilityReadAnythingOmniboxIconLabelShownCount = 100246, (deprecated)
  kApplicationLocale = 100247,
  kListenToThisPageEnabled = 100248,
  // kIpProtectionEnabled = 100249, (deprecated)
  kAccessibilityReadAnythingLinksEnabled = 100250,
  kProfileContentSettingsPartitionedExceptionsAntiAbuse = 100251,
  kProfileContentSettingsPartitionedExceptionsAutomaticDownloads = 100252,
  kProfileContentSettingsPartitionedExceptionsCookies = 100253,
  kProfileContentSettingsPartitionedExceptionsGetDisplayMediaSetSelectAllScreens =
      100254,
  kProfileContentSettingsPartitionedExceptionsImages = 100255,
  kProfileContentSettingsPartitionedExceptionsJavascript = 100256,
  kProfileContentSettingsPartitionedExceptionsLocalFonts = 100257,
  kProfileContentSettingsPartitionedExceptionsMouselock = 100258,
  kProfileContentSettingsPartitionedExceptionsPopups = 100259,
  kProfileContentSettingsPartitionedExceptionsWindowPlacement = 100260,
  // kStandaloneWindowMigrationNudgeShown = 100261, (deprecated)
  kTabDiscardingExceptionsWithTime = 100262,
  kAccessibilityFaceGazeCursorSpeedUp = 100263,
  kAccessibilityFaceGazeCursorSpeedDown = 100264,
  kAccessibilityFaceGazeCursorSpeedLeft = 100265,
  kAccessibilityFaceGazeCursorSpeedRight = 100266,
  // kAccessibilityFaceGazeCursorSmoothing = 100267, (deprecated)
  kAccessibilityFaceGazeCursorUseAcceleration = 100268,
  // kFingerprintingProtectionEnabled = 100269, (deprecated)
  kAccessibilityFaceGazeGesturesToMacros = 100270,
  kAccessibilityFaceGazeGesturesToConfidence = 100271,
  kShelfGeminiAppPinRolls = 100272,
  kProfileContentSettingsExceptionsTrackingProtection = 100273,
  kProfileContentSettingsPartitionedExceptionsTrackingProtection = 100274,
  kProfileDefaultContentSettingValuesTrackingProtection = 100275,
  kShowForwardButton = 100276,
  kAccessibilityMagnifierFollowsSts = 100277,
  kAccessibilityReadAnythingLanguagesEnabled = 100278,
  kKeyboardDefaultSplitModifierSettings = 100279,
  kDisplayAmbientLightSensorLastEnabled = 100280,
  kAccessibilityMainNodeAnnotationsEnabled = 100281,
  // kSyncableVersionedWallpaperInfo = 100282, (deprecated)
  kFocusModeSelectedTask = 100283,
  kFocusModeSoundSection = 100284,
  kAccessibilityFaceGazeActionsEnabled = 100285,
  kAccessibilityFaceGazeCursorControlEnabled = 100286,
  kAccessibilityFaceGazeAdjustSpeedSeparately = 100287,
  kKeyboardAmbientLightSensorLastEnabled = 100288,
  kAccessibilityReadAnythingImagesEnabled = 100289,
  kShelfMallAppPinRolls = 100290,
  // kDesktopToiOSAddressPromoLastImpressionTimestamp = 100291, (deprecated)
  // kDesktopToiOSAddressPromoImpressionsCounter = 100292, (deprecated)
  // kDesktopToiOSAddressPromoOptOut = 100293, (deprecated)
  kMahiNudgeShownCount = 100294,
  kAccessibilityMagnifierFollowsChromeVox = 100295,
  kKeyboardHasSplitModifierKeyboard = 100296,
  kHttpsFirstBalancedMode = 100297,
  kAccessibilityFlashNotificationsEnabled = 100298,
  kAccessibilityFlashNotificationsColor = 100299,
  kPinnedChromeLabsMigrationComplete = 100300,
  kAccessibilityFaceGazeGesturesToKeyCombos = 100301,
  kFocusModeYTMDisplayOAuthConsent = 100302,
  kFocusModeYTMDisplayFreeTrial = 100303,
  kAccessibilityFaceGazeVelocityThreshold = 100304,
  // kDesktopToiOSPaymentPromoLastImpressionTimestamp = 100305, (deprecated)
  // kDesktopToiOSPaymentPromoImpressionsCounter = 100306, (deprecated)
  // kDesktopToiOSPaymentPromoOptOut = 100307, (deprecated)
  // kDesktopToiOSNtpPromoAppearanceTimestamps = 100308, (deprecated)
  // kDesktopToiOSNtpPromoDismissed = 100309, (deprecated)
  // kPrivacySandboxFakeNoticePromptShownTimeSync = 100310, (deprecated)
  kAccessibilityBounceKeysDelayMs = 100311,
  kAccessibilitySlowKeysDelayMs = 100312,
  kAccessibilityFaceGazePrecisionClick = 100313,
  kAccessibilityFaceGazePrecisionClickSpeedFactor = 100314,
  kOfficeFilesAlwaysMoveToDriveSyncable = 100315,
  kOfficeFilesAlwaysMoveToOneDriveSyncable = 100316,
  kOfficeMoveConfirmationShownForDriveSyncable = 100317,
  kOfficeMoveConfirmationShownForOneDriveSyncable = 100318,
  kOfficeMoveConfirmationShownForLocalToDriveSyncable = 100319,
  kOfficeMoveConfirmationShownForLocalToOneDriveSyncable = 100320,
  kOfficeMoveConfirmationShownForCloudToDriveSyncable = 100321,
  kOfficeMoveConfirmationShownForCloudToOneDriveSyncable = 100322,
  kPinnedCastMigrationComplete = 100323,
  kAccessibilityAXTreeFixingEnabled = 100324,
  kTabSearchMigrationComplete = 100325,
  kReadAloudPlaybackMode = 100326,
  kPinSplitTabButton = 100327,
  kGlicRolloutEligibility = 100328,
  kShelfNotebookLmAppPinRolls = 100329,
  // kVerticalTabsEnabled = 100330, (no longer synced)
  kSplitViewDragAndDropEnabled = 100331,
  // kDesktopToiOSEnhancedBrowsingPromoLastImpressionTimestamp = 100332, (deprecated)
  // kDesktopToiOSEnhancedBrowsingPromoImpressionsCounter = 100333, (deprecated)
  // kDesktopToiOSEnhancedBrowsingPromoOptOut = 100334, (deprecated)
  // kDesktopToiOSLensPromoLastImpressionTimestamp = 100335, (deprecated)
  // kDesktopToiOSLensPromoImpressionsCounter = 100336, (deprecated)
  // kDesktopToiOSLensPromoOptOut = 100337, (deprecated)
  kSubscriptionEligibilityAiSubscriptionTier = 100338,
  kAccessibilityCursorHighlightEnabled = 100339,
  kAccessibilityCursorColorEnabled = 100340,
  kAccessibilityCursorColor = 100341,
  kAccessibilityLargeCursorEnabled = 100342,
  kAccessibilityLargeCursorDipSize = 100343,
  kAccessibilityHighContrastEnabled = 100344,
  kAccessibilityCaretHighlightEnabled = 100345,
  kAccessibilityCaretBlinkInterval = 100346,
  kAccessibilityFocusHighlightEnabled = 100347,
  kAccessibilityColorCorrectionHasBeenSetup = 100348,
  kHighContrastAcceleratorDialogHasBeenAccepted = 100349,
  kAccessibilityReducedAnimationsEnabled = 100350,
  kAccessibilityCaptionsTextSize = 100351,
  kAccessibilityCaptionsTextFont = 100352,
  kAccessibilityCaptionsTextColor = 100353,
  kAccessibilityCaptionsTextOpacity = 100354,
  kAccessibilityCaptionsBackgroundColor = 100355,
  kAccessibilityCaptionsTextShadow = 100356,
  kAccessibilityCaptionsBackgroundOpacity = 100357,
  kAccessibilityScreenMagnifierEnabled = 100358,
  kAccessibilitySelectToSpeakEnabled = 100359,
  kDockedMagnifierEnabled = 100360,
  kDockedMagnifierScale = 100361,
  kScreenMagnifierAcceleratorDialogHasBeenAccepted = 100362,
  kDockedMagnifierAcceleratorDialogHasBeenAccepted = 100363,
  kSelectToSpeakAcceleratorDialogHasBeenAccepted = 100364,
  kAccessibilityScreenMagnifierScale = 100365,
  // kIOSPromoReminder = 100366, (deprecated, moved to common syncable prefs)
  kClassManagementToolsOOBEAccessCountSetting = 100367,
  kClassManagementToolsKioskReceiverCodes = 100368,
  kPinContextualTaskButton = 100369,
  kAccessibilityReadAnythingOmniboxChipIgnoredCount = 100370,
  kAccessibilityReadAnythingLineFocus = 100371,
  kProjectsPanelEntrypointEnabled = 100372,
  // kDesktopToiOSTabGroupsPromoLastImpressionTimestamp = 100373, (deprecated)
  // kDesktopToiOSTabGroupsPromoImpressionsCounter = 100374, (deprecated)
  // kDesktopToiOSTabGroupsPromoOptOut = 100375, (deprecated)
  // kDesktopToiOSPriceTrackingPromoLastImpressionTimestamp = 100376, (deprecated)
  // kDesktopToiOSPriceTrackingPromoImpressionsCounter = 100377, (deprecated)
  // kDesktopToiOSPriceTrackingPromoOptOut = 100378, (deprecated)
  kAccessibilityReadAnythingLastNonDisabledLineFocus = 100379,
  // See components/sync_preferences/README.md about adding new entries here.
  // vvvvv IMPORTANT! vvvvv
  // Note to the reviewer: IT IS YOUR RESPONSIBILITY to ensure that new syncable
  // prefs follow privacy guidelines! See the readme file linked above for
  // guidance and escalation path in case anything is unclear.
  // ^^^^^ IMPORTANT! ^^^^^
};
// LINT.ThenChange(/tools/metrics/histograms/metadata/sync/enums.xml:ChromeSyncablePref)
}  // namespace syncable_prefs_ids

// Non-iOS specific list of syncable preferences.
constexpr auto kChromeSyncablePrefsAllowlist = base::MakeFixedFlatMap<
    std::string_view,
    sync_preferences::SyncablePrefMetadata>({
    {prefs::kAccessibilityReadAnythingFontName,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontName,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingFontScale,
     {syncable_prefs_ids::kAccessibilityReadAnythingFontScale,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingColorInfo,
     {syncable_prefs_ids::kAccessibilityReadAnythingColorInfo,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLineSpacing,
     {syncable_prefs_ids::kAccessibilityReadAnythingLineSpacing,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLetterSpacing,
     {syncable_prefs_ids::kAccessibilityReadAnythingLetterSpacing,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingVoiceName,
     {syncable_prefs_ids::kAccessibilityReadAnythingVoiceName,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingSpeechRate,
     {syncable_prefs_ids::kAccessibilityReadAnythingSpeechRate,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingHighlightGranularity,
     {syncable_prefs_ids::kAccessibilityReadAnythingHighlightGranularity,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLinksEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingLinksEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingImagesEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingImagesEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLanguagesEnabled,
     {syncable_prefs_ids::kAccessibilityReadAnythingLanguagesEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingOmniboxChipIgnoredCount,
     {syncable_prefs_ids::kAccessibilityReadAnythingOmniboxChipIgnoredCount,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLineFocus,
     {syncable_prefs_ids::kAccessibilityReadAnythingLineFocus,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityReadAnythingLastNonDisabledLineFocus,
     {syncable_prefs_ids::kAccessibilityReadAnythingLastNonDisabledLineFocus,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLensRegionSearchEnabled,
     {syncable_prefs_ids::kLensRegionSearchEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHatsSurveyMetadata,
     {syncable_prefs_ids::kHatsSurveyMetadata, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHomePage,
     {syncable_prefs_ids::kHomePage, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHomePageIsNewTabPage,
     {syncable_prefs_ids::kHomePageIsNewTabPage, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDeprecatedNtpCustomBackgroundDictDoNotUse,
     {syncable_prefs_ids::kNtpCustomBackgroundDict, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionBubbleExpanded,
     {syncable_prefs_ids::kLiveCaptionBubbleExpanded, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionEnabled,
     {syncable_prefs_ids::kLiveCaptionEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionLanguageCode,
     {syncable_prefs_ids::kLiveCaptionLanguageCode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionMediaFoundationRendererErrorSilenced,
     {syncable_prefs_ids::kLiveCaptionMediaFoundationRendererErrorSilenced,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kLiveCaptionMaskOffensiveWords,
     {syncable_prefs_ids::kLiveCaptionMaskOffensiveWords, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShowHomeButton,
     {syncable_prefs_ids::kShowHomeButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kShowForwardButton,
     {syncable_prefs_ids::kShowForwardButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinContextualTaskButton,
     {syncable_prefs_ids::kPinContextualTaskButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinSplitTabButton,
     {syncable_prefs_ids::kPinSplitTabButton, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kSplitViewDragAndDropEnabled,
     {syncable_prefs_ids::kSplitViewDragAndDropEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinnedActions,
     {syncable_prefs_ids::kPinnedActions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {prefs::kPinnedSearchCompanionMigrationComplete,
     {syncable_prefs_ids::kPinnedSearchCompanionMigrationComplete,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinnedChromeLabsMigrationComplete,
     {syncable_prefs_ids::kPinnedChromeLabsMigrationComplete,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPinnedCastMigrationComplete,
     {syncable_prefs_ids::kPinnedCastMigrationComplete, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kTabSearchMigrationComplete,
     {syncable_prefs_ids::kTabSearchMigrationComplete, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kProjectsPanelEntrypointEnabled,
     {syncable_prefs_ids::kProjectsPanelEntrypointEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#if BUILDFLAG(ENABLE_EXTENSIONS_CORE)
    {extensions::pref_names::kPinnedExtensions,
     {syncable_prefs_ids::kPinnedExtensions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kSupervisedUserApprovedExtensions,
     {syncable_prefs_ids::kSupervisedUserApprovedExtensions,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif  // BUILDFLAG(ENABLE_EXTENSIONS_CORE)
#if BUILDFLAG(IS_MAC)
    {prefs::kShowFullscreenToolbar,
     {syncable_prefs_ids::kShowFullscreenToolbar, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAllowJavascriptAppleEvents,
     {syncable_prefs_ids::kAllowJavascriptAppleEvents, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
#endif
    {performance_manager::user_tuning::prefs::kTabDiscardingExceptions,
     {syncable_prefs_ids::kTabDiscardingExceptions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kNone}},
    {performance_manager::user_tuning::prefs::kTabDiscardingExceptionsWithTime,
     {syncable_prefs_ids::kTabDiscardingExceptionsWithTime, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsEnabled,
     {syncable_prefs_ids::kAccessibilityImageLabelsEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityImageLabelsOptInAccepted,
     {syncable_prefs_ids::kAccessibilityImageLabelsOptInAccepted,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityAXTreeFixingEnabled,
     {syncable_prefs_ids::kAccessibilityAXTreeFixingEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kAccessibilityMainNodeAnnotationsEnabled,
     {syncable_prefs_ids::kAccessibilityMainNodeAnnotationsEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDeprecatedBrowserColorSchemeDoNotUse,
     {syncable_prefs_ids::kBrowserColorScheme, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDeprecatedBrowserColorVariantDoNotUse,
     {syncable_prefs_ids::kBrowserColorVariant, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDefaultCharset,
     {syncable_prefs_ids::kDefaultCharset, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDevToolsSyncPreferences,
     {syncable_prefs_ids::kDevToolsSyncPreferences, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDevToolsSyncedPreferencesSyncEnabled,
     {syncable_prefs_ids::kDevToolsSyncedPreferencesSyncEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kEnableDoNotTrack,
     {syncable_prefs_ids::kEnableDoNotTrack, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kExtensionCommands,
     {syncable_prefs_ids::kExtensionCommands, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kExtensionsUIDeveloperMode,
     {syncable_prefs_ids::kExtensionsUIDeveloperMode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kDeprecatedGrayscaleThemeEnabledDoNotUse,
     {syncable_prefs_ids::kGrayscaleThemeEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsOnlyModeEnabled,
     {syncable_prefs_ids::kHttpsOnlyModeEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kNetworkEasterEggHighScore,
     {syncable_prefs_ids::kNetworkEasterEggHighScore, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kCustom}},
    {prefs::kNetworkPredictionOptions,
     {syncable_prefs_ids::kNetworkPredictionOptions, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kNetworkQualities,
     {syncable_prefs_ids::kNetworkQualities, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPerformanceTracingEnabled,
     {syncable_prefs_ids::kPerformanceTracingEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPluginsAlwaysOpenPdfExternally,
     {syncable_prefs_ids::kPluginsAlwaysOpenPdfExternally, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPrivacySandboxRelatedWebsiteSetsEnabled,
     {syncable_prefs_ids::kPrivacySandboxRelatedWebsiteSetsEnabled,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kPromptForDownload,
     {syncable_prefs_ids::kPromptForDownload, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kProtectedContentDefault,
     {syncable_prefs_ids::kProtectedContentDefault, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kRestoreOnStartup,
     {syncable_prefs_ids::kRestoreOnStartup, syncer::PREFERENCES,
      // This is behind history opt-in to be consistent with the
      // `kURLsToRestoreOnStartup` pref.
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kSearchSuggestEnabled,
     {syncable_prefs_ids::kSearchSuggestEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kURLsToRestoreOnStartup,
     {syncable_prefs_ids::kURLsToRestoreOnStartup, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableListWithRewriteOnUpdate}},
    {prefs::kDeprecatedUserColorDoNotUse,
     {syncable_prefs_ids::kUserColor, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    // The following prefs are constructed from a prefix in
    // website_settings_info and are registered in
    // content_settings_registry.
    {"profile.content_settings.exceptions.anti_abuse",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsAntiAbuse,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.automatic_downloads",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsAutomaticDownloads,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.cookies",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsCookies,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.get_display_media_set_select_all_"
     "screens",
     {syncable_prefs_ids::
          kProfileContentSettingsExceptionsGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.images",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsImages,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.javascript",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsJavascript,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.local_fonts",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsLocalFonts,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.mouselock",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsMouselock,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.popups",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsPopups,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.tracking_protection",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsTrackingProtection,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.exceptions.window_placement",
     {syncable_prefs_ids::kProfileContentSettingsExceptionsWindowPlacement,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.anti_abuse",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsAntiAbuse,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.automatic_downloads",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsAutomaticDownloads,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.cookies",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsCookies,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.get_display_media_set_"
     "select_all_screens",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.images",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsImages,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.javascript",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsJavascript,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.local_fonts",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsLocalFonts,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.mouselock",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsMouselock,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.popups",
     {syncable_prefs_ids::kProfileContentSettingsPartitionedExceptionsPopups,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.tracking_protection",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsTrackingProtection,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.content_settings.partitioned_exceptions.window_placement",
     {syncable_prefs_ids::
          kProfileContentSettingsPartitionedExceptionsWindowPlacement,
      syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kSensitiveRequiresHistory,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.default_content_setting_values.anti_abuse",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesAntiAbuse,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.automatic_downloads",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesAutomaticDownloads,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.cookies",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesCookies,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.get_display_media_set_select_"
     "all_screens",
     {syncable_prefs_ids::
          kProfileDefaultContentSettingValuesGetDisplayMediaSetSelectAllScreens,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.images",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesImages,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.javascript",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesJavascript,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.local_fonts",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesLocalFonts,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.mouselock",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesMouselock,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.popups",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesPopups,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {"profile.default_content_setting_values.tracking_protection",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesTrackingProtection,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kMergeableDict}},
    {"profile.default_content_setting_values.window_placement",
     {syncable_prefs_ids::kProfileDefaultContentSettingValuesWindowPlacement,
      syncer::PREFERENCES, sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    // This is not exposed in a header.
    // TODO(crbug.com/40896017): Declare this in the corresponding header.
    {"webauthn.cablev2_pairings",
     {syncable_prefs_ids::kWebauthnCablev2Pairings, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kBlockAll3pcToggleEnabled,
     {syncable_prefs_ids::kBlockAll3pcToggleEnabled, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsFirstModeIncognito,
     {syncable_prefs_ids::kHttpsFirstModeIncognito, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {prefs::kHttpsFirstBalancedMode,
     {syncable_prefs_ids::kHttpsFirstBalancedMode, syncer::PREFERENCES,
      sync_preferences::PrefSensitivity::kNone,
      sync_preferences::MergeBehavior::kNone}},
    {glic::prefs::kGlicRolloutEligibility,
     {syncable_prefs_ids::kGlicRolloutEligibility, syncer::PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kExemptFromUserControlWhileSignedIn,
      sync_preferences::MergeBehavior::kNone}},
    {subscription_eligibility::prefs::kAiSubscriptionTier,
     {syncable_prefs_ids::kSubscriptionEligibilityAiSubscriptionTier,
      syncer::PRIORITY_PREFERENCES,
      sync_preferences::PrefSensitivity::kExemptFromUserControlWhileSignedIn,
      sync_preferences::MergeBehavior::kNone}},
});

}  // namespace

std::optional<sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetSyncablePrefMetadata(
    std::string_view pref_name) const {
  const auto it = kChromeSyncablePrefsAllowlist.find(pref_name);
  if (it != kChromeSyncablePrefsAllowlist.end()) {
    DCHECK(!common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name)
                .has_value());
    return it->second;
  }
  // Check in `common_syncable_prefs_database_`.
  return common_syncable_prefs_database_.GetSyncablePrefMetadata(pref_name);
}

std::map<std::string_view, sync_preferences::SyncablePrefMetadata>
ChromeSyncablePrefsDatabase::GetAllSyncablePrefsForTest() const {
  std::map<std::string_view, sync_preferences::SyncablePrefMetadata>
      syncable_prefs;
  std::ranges::copy(kChromeSyncablePrefsAllowlist,
                    std::inserter(syncable_prefs, syncable_prefs.end()));
  std::ranges::move(
      common_syncable_prefs_database_.GetAllSyncablePrefsForTest(),  // IN-TEST
      std::inserter(syncable_prefs, syncable_prefs.end()));
  return syncable_prefs;
}
}  // namespace browser_sync
