# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")
import("//third_party/jni_zero/jni_zero.gni")
import("//tools/grit/grit_rule.gni")

source_set("supervised_user") {
  sources = []
  public_deps = []

  if (enable_extensions_core) {
    sources += [ "supervised_user_extensions_metrics_recorder.h" ]
    public_deps += [ "//extensions/browser" ]
  }
}

static_library("test_support") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [
    "supervised_user_browsertest_base.cc",
    "supervised_user_browsertest_base.h",
    "supervised_user_test_util.cc",
    "supervised_user_test_util.h",
  ]

  public_deps = [ "//chrome/browser/signin" ]

  deps = [
    "//chrome/browser",
    "//chrome/browser:browser_process",
    "//chrome/browser:global_features",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sync",
    "//chrome/common:constants",
    "//components/content_settings/core/browser",
    "//components/prefs",
    "//components/signin/public/identity_manager",
    "//components/signin/public/identity_manager:test_support",
    "//components/supervised_user/core/browser",
    "//components/supervised_user/core/browser:device_parental_controls",
    "//components/supervised_user/core/browser:test_support",
    "//components/supervised_user/core/common",
    "//components/supervised_user/test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]

  deps += [ "//chrome/test:test_support_ui" ]
}
