# Copyright 2019 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//media/media_options.gni")

source_set("generator") {
  deps = [
    "//base",
    "//cc",
    "//chrome/browser/image_decoder",
    "//chrome/common",
    "//chrome/services/media_gallery_util/public/cpp",
    "//chrome/services/media_gallery_util/public/mojom",
    "//content/public/browser",
    "//media",
    "//mojo/public/cpp/bindings",
    "//skia",
    "//ui/gfx",
  ]

  sources = [
    "image_thumbnail_request.cc",
    "image_thumbnail_request.h",
    "thumbnail_util.cc",
    "thumbnail_util.h",
  ]
}
