# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("internal") {
  public_deps = [
    ":comments_internal",
    ":core_internal",
    ":messaging_internal",
  ]
}

static_library("core_internal") {
  visibility = [
    ":*",
    "//chrome/browser",
    "//chrome/browser/collaboration:*",
    "//chrome/test:*",
    "//ios/chrome/browser/collaboration/model",
    "//ios/chrome/browser/data_sharing/model",
  ]

  sources = [
    "collaboration_controller.cc",
    "collaboration_controller.h",
    "collaboration_service_impl.cc",
    "collaboration_service_impl.h",
    "empty_collaboration_service.cc",
    "empty_collaboration_service.h",
    "metrics.cc",
    "metrics.h",
  ]

  deps = [
    "//components/data_sharing/public:group_data",
    "//components/data_sharing/public:logger",
    "//components/sync/service",
    "//ui/base",
  ]

  public_deps = [
    "//base",
    "//components/collaboration/public",
    "//components/collaboration/public:prefs",
    "//components/data_sharing/public",
    "//components/keyed_service/core",
  ]
}

source_set("collaboration_finder") {
  sources = [
    "collaboration_finder_impl.cc",
    "collaboration_finder_impl.h",
  ]

  deps = [
    "//base",
    "//components/data_sharing/public",
    "//components/saved_tab_groups/public",
  ]
}

static_library("comments_internal") {
  sources = [
    "comments/comments_service_impl.cc",
    "comments/comments_service_impl.h",
    "comments/empty_comments_service.cc",
    "comments/empty_comments_service.h",
  ]

  deps = [
    "//base",
    "//components/collaboration/public:comments_public",
    "//components/keyed_service/core",
  ]
}

static_library("messaging_internal") {
  sources = [
    "messaging/configuration.cc",
    "messaging/configuration.h",
    "messaging/data_sharing_change_notifier.cc",
    "messaging/data_sharing_change_notifier.h",
    "messaging/data_sharing_change_notifier_impl.cc",
    "messaging/data_sharing_change_notifier_impl.h",
    "messaging/instant_message_processor.h",
    "messaging/instant_message_processor_impl.cc",
    "messaging/instant_message_processor_impl.h",
    "messaging/messaging_backend_service_impl.cc",
    "messaging/messaging_backend_service_impl.h",
    "messaging/storage/collaboration_message_util.cc",
    "messaging/storage/collaboration_message_util.h",
    "messaging/storage/empty_messaging_backend_database.cc",
    "messaging/storage/empty_messaging_backend_database.h",
    "messaging/storage/messaging_backend_database.cc",
    "messaging/storage/messaging_backend_database.h",
    "messaging/storage/messaging_backend_database_impl.cc",
    "messaging/storage/messaging_backend_database_impl.h",
    "messaging/storage/messaging_backend_store.h",
    "messaging/storage/messaging_backend_store_impl.cc",
    "messaging/storage/messaging_backend_store_impl.h",
    "messaging/tab_group_change_notifier.cc",
    "messaging/tab_group_change_notifier.h",
    "messaging/tab_group_change_notifier_impl.cc",
    "messaging/tab_group_change_notifier_impl.h",
  ]

  deps = [
    "//base",
    "//components/collaboration/internal/messaging/storage/protocol",
    "//components/collaboration/public:empty_messaging_backend_service",
    "//components/collaboration/public:messaging_public",
    "//components/data_sharing/public",
    "//components/saved_tab_groups/public",
    "//components/sqlite_proto",
    "//components/strings",
    "//components/url_formatter",
    "//google_apis",
    "//sql",
    "//ui/base",
  ]
}

group("unit_tests") {
  testonly = true

  visibility = [ "//components/collaboration:unit_tests" ]

  deps = [
    ":collaboration_finder_unit_tests",
    ":comments_unit_tests",
    ":core_unit_tests",
    ":messaging_unit_tests",
  ]
}

source_set("core_unit_tests") {
  testonly = true

  visibility = [ ":*" ]

  sources = [
    "collaboration_controller_unittest.cc",
    "collaboration_service_impl_unittest.cc",
    "empty_collaboration_service_unittest.cc",
  ]

  deps = [
    ":internal",
    "//base/test:test_support",
    "//components/collaboration:test_support",
    "//components/data_sharing:test_support",
    "//components/data_sharing/public",
    "//components/saved_tab_groups/test_support",
    "//components/signin/public/identity_manager:test_support",
    "//components/sync:test_support",
    "//testing/gtest",
  ]

  # TODO(crbug.com/40031409): Fix code that adds exit-time destructors and
  # enable the diagnostic by removing this line.
  configs += [ "//build/config/compiler:no_exit_time_destructors" ]
}

source_set("comments_unit_tests") {
  testonly = true

  visibility = [ ":*" ]

  sources = [
    "comments/comments_service_impl_unittest.cc",
    "comments/empty_comments_service_unittest.cc",
  ]

  deps = [
    ":comments_internal",
    "//base",
    "//base/test:test_support",
    "//components/collaboration/public:comments_public",
    "//testing/gtest",
  ]
}

source_set("messaging_unit_tests") {
  testonly = true
  sources = [
    "messaging/data_sharing_change_notifier_impl_unittest.cc",
    "messaging/instant_message_processor_impl_unittest.cc",
    "messaging/messaging_backend_service_impl_unittest.cc",
    "messaging/storage/messaging_backend_database_impl_unittest.cc",
    "messaging/storage/messaging_backend_store_impl_unittest.cc",
    "messaging/tab_group_change_notifier_impl_unittest.cc",
  ]
  deps = [
    ":messaging_internal",
    "//base",
    "//base/test:test_support",
    "//components/collaboration:test_support",
    "//components/collaboration/internal/messaging/storage/protocol",
    "//components/collaboration/public:messaging_public",
    "//components/data_sharing:test_support",
    "//components/data_sharing/public",
    "//components/saved_tab_groups/public",
    "//components/saved_tab_groups/test_support",
    "//components/signin/public/identity_manager:test_support",
    "//components/tab_groups",
    "//testing/gmock",
    "//testing/gtest",
  ]
}

source_set("collaboration_finder_unit_tests") {
  testonly = true

  sources = [ "collaboration_finder_impl_unittest.cc" ]

  deps = [
    ":collaboration_finder",
    "//base/test:test_support",
    "//components/data_sharing:test_support",
    "//components/data_sharing/public",
    "//components/saved_tab_groups/public",
    "//testing/gtest",
  ]
}
