# Copyright 2018 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("multi_process") {
  sources = [
    "client_connection_manager.cc",
    "client_connection_manager.h",
    "supervisor.cc",
    "supervisor.h",
  ]

  deps = [
    "//base",
    "//components/services/heap_profiling",
    "//components/services/heap_profiling/public/cpp",
    "//content/public/browser",
    "//content/public/common",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "test_driver.cc",
    "test_driver.h",
  ]

  deps = [
    ":multi_process",
    "//base",
    "//base/allocator/partition_allocator/src/partition_alloc:test_support",
    "//base/test:test_support",
    "//components/services/heap_profiling/public/cpp",
    "//content/public/browser",
    "//content/public/common",
  ]
}
