# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(b/358211208): Re-enable when shared_library is properly used.
# allow_internal = is_chrome_branded
allow_internal = false

source_set("reading") {
  sources = [ "reading/distillable_pages.h" ]

  if (allow_internal) {
    sources += [ "internal/reading/distillable_pages.cc" ]
  } else {
    sources += [ "reading/distillable_pages.cc" ]
  }

  deps = [
    "//base",
    "//url",
  ]
}

source_set("penguin") {
  sources = [
    "penguin/penguin_client.cc",
    "penguin/penguin_client.h",
  ]

  deps = [
    "//base",
    "//content/public/browser",
  ]
}
