# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/signin/features.gni")
import("//extensions/buildflags/buildflags.gni")

assert(!is_fuchsia, "Fuchsia shouldn't use anything in //chrome")

source_set("path_parser") {
  sources = [ "policy_path_parser.h" ]

  if (is_chromeos || is_linux) {
    sources += [ "policy_path_parser_linux.cc" ]
  } else if (is_mac) {
    sources += [ "policy_path_parser_mac.mm" ]
  }

  deps = [
    "//base",
    "//chrome/common:constants",
    "//components/policy:generated",
    "//components/strings:components_strings",
  ]

  if (is_mac) {
    deps += [ "//build:branding_buildflags" ]
  }
}

source_set("onc") {
  sources = []

  deps = []
}

source_set("system_features_disable_list") {
  sources = []
}

source_set("policy_util") {
  sources = [
    "policy_util.cc",
    "policy_util.h",
  ]

  public_deps = [ "//base" ]

  deps = [
    "//components/content_settings/core/common",
    "//components/invalidation",
    "//components/policy/core/common",
    "//components/policy/core/common:common_constants",
    "//components/prefs",
    "//url",
  ]
}

if (enable_extensions) {
  source_set("policy_migrator") {
    sources = [
      "chrome_extension_policy_migrator.cc",
      "chrome_extension_policy_migrator.h",
    ]
    public_deps = [ "//components/policy/core/common" ]
    deps = [
      "//base",
      "//components/strings:components_strings",
      "//extensions/common",
    ]
  }
}

source_set("test_support") {
  testonly = true

  sources = [
    "cloud/cloud_policy_test_utils.cc",
    "cloud/cloud_policy_test_utils.h",
    "policy_test_utils.cc",
    "policy_test_utils.h",
    "safe_browsing_policy_test.cc",
    "safe_browsing_policy_test.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/lifetime:termination_notification",
    "//chrome/test:test_support",
    "//components/policy/core/common",
    "//components/policy/core/common:common_constants",
    "//components/safe_search_api",
    "//components/security_interstitials/content:security_interstitial_page",
    "//url",
  ]

  if (enable_dice_support) {
    sources += [
      "cloud/user_policy_signin_service_test_util.cc",
      "cloud/user_policy_signin_service_test_util.h",
    ]
  }

  if (enable_extensions_core) {
    sources += [
      "cloud/mock_extension_install_policy_service.cc",
      "cloud/mock_extension_install_policy_service.h",
      "extension_policy_test_base.cc",
      "extension_policy_test_base.h",
    ]
    deps += [ "//extensions/common" ]
  }

  sources += [
    "policy_test_utils_desktop.cc",
    "safe_search_policy_test.cc",
    "safe_search_policy_test.h",
    "url_blocking_policy_test_utils.cc",
    "url_blocking_policy_test_utils.h",
  ]

  deps += [
    "//chrome/browser/preloading:test_support",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/ui/location_bar",
    "//chrome/common:constants",
    "//chrome/common/net",
    "//components/omnibox/browser",
    "//components/policy/core/browser",
    "//components/policy/core/common:test_support",
    "//components/security_interstitials/core",
    "//components/variations:test_support",
    "//content/public/browser",
    "//content/public/common",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//net",
    "//net:test_support",
    "//services/network/public/mojom",
    "//ui/snapshot",
  ]
}

# Browser tests for specific policies.
source_set("policy_specific_browser_tests") {
  testonly = true

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "policy_network_browsertest.cc",
    "site_isolation_policy_browsertest.cc",
    "test/autoplay_policy_browsertest.cc",
    "test/back_forward_cache_policy_browsertest.cc",
    "test/certificate_transparency_policy_browsertest.cc",
    "test/force_permission_policy_unload_default_enabled_policy_browsertest.cc",
    "test/hsts_policy_browsertest.cc",
    "test/network_prediction_policy_browsertest.cc",
    "test/policy_statistics_collector_browsertest.cc",
    "test/proxy_policies_browsertest.cc",
    "test/safe_browsing_policy_browsertest.cc",
    "test/shared_clipboard_enabled_browsertest.cc",
    "test/ssl_error_overriding_allowed_policy_browsertest.cc",
    "test/standardized_browser_zoom_browsertest.cc",
    "test/url_keyed_anonymized_data_collection_enabled_browsertest.cc",
    "test/web_rtc_udp_port_range_policy_browsertest.cc",
    "test/xslt_policy_browsertest.cc",
  ]

  deps = [
    ":test_support",
    "//base",
    "//chrome/app:command_ids",
    "//chrome/browser",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/media/webrtc",
    "//chrome/browser/preloading:prefs",
    "//chrome/browser/ui/autofill",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/content_settings/core/browser",
    "//components/content_settings/core/common",
    "//components/heap_profiling/in_process",
    "//components/policy/core/common",
    "//components/prefs",
    "//components/proxy_config",
    "//components/safe_browsing/core/common",
    "//components/security_interstitials/content:security_interstitial_page",
    "//components/site_isolation",
    "//components/unified_consent",
    "//content/test:test_support",
    "//media",
    "//testing/gmock",
  ]

  sources += [
    "test/autofill_ai_policy_browsertest.cc",
    "test/autofill_policy_browsertest.cc",
    "test/automatic_fullscreen_policy_browsertest.cc",
    "test/bookmark_bar_enabled_browsertest.cc",
    "test/clear_window_name_for_new_browsing_context_group_browsertest.cc",
    "test/component_updater_policy_browsertest.cc",
    "test/data_url_policy_browsertest.cc",
    "test/developer_tools_policy_browsertest.cc",
    "test/download_directory_browsertest.cc",
    "test/happy_eyeballs_v3_enabled_policy_browsertest.cc",
    "test/ipv6_reachability_override_policy_browsertest.cc",
    "test/legacy_cookie_scope_browsertest.cc",
    "test/local_fonts_policy_browsertest.cc",
    "test/media_stream_policy_browsertest.cc",
    "test/partitioned_blob_url_browsertest.cc",
    "test/quic_allowed_browsertest.cc",
    "test/shared_dictionary_policy_browsertest.cc",
    "test/signed_exchange_browsertest.cc",
    "test/static_storage_quota_policy_browsertest.cc",
    "test/task_manager_end_process_enabled_browsertest.cc",
    "test/web_rtc_event_log_collection_allowed_policy_browsertest.cc",
    "test/web_rtc_local_ips_allowed_urls_policy_browsertest.cc",
    "test/web_rtc_text_log_collection_allowed_policy_browsertest.cc",
    "test/window_management_policy_browsertest.cc",
  ]

  deps += [
    "//chrome/browser/autofill",
    "//chrome/browser/devtools",
    "//chrome/browser/devtools:test_support",
    "//chrome/browser/profiles",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/task_manager",
    "//chrome/browser/ui/browser_window",
    "//components/autofill/content/browser:test_support",
    "//components/autofill/core/browser",
    "//components/bookmarks/common",
    "//components/enterprise",
    "//components/enterprise:test_support",
    "//components/policy:chrome_settings_proto_generated_compile",
    "//components/policy/core/browser",
    "//components/policy/core/common:common_constants",
    "//components/policy/proto",
    "//components/policy/test_support",
    "//components/search",
    "//components/webrtc",
  ]

  sources += [
    "policy_startup_browsertest.cc",
    "test/network_time_policy_browsertest.cc",
  ]

  sources += [ "test/variation_restrict_parameter_policy_browsertest.cc" ]
  deps += [ "//components/variations/service" ]
}

source_set("browser_tests") {
  testonly = true

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [
    "cloud/cloud_policy_browsertest.cc",
    "cloud/cloud_policy_manager_browsertest.cc",
    "cloud/device_management_service_browsertest.cc",
    "test/accessibility_policy_browsertest.cc",
  ]

  data_deps = [ "//components/policy:policy_templates" ]

  deps = [
    ":policy_specific_browser_tests",
    ":test_support",
    "//base",
    "//build:branding_buildflags",
    "//chrome/browser",
    "//chrome/browser:main_extra_parts",
    "//chrome/browser/background",
    "//chrome/browser/invalidation",
    "//chrome/browser/policy:policy_util",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/search",
    "//chrome/browser/signin",
    "//chrome/browser/ui:ui_features",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/enterprise",
    "//components/enterprise:test_support",
    "//components/invalidation:legacy_topics_cleanup",
    "//components/invalidation:test_support",
    "//components/keyed_service/core",
    "//components/policy:chrome_settings_proto_generated_compile",
    "//components/policy/core/browser",
    "//components/policy/core/common",
    "//components/policy/core/common:common_constants",
    "//components/policy/proto",
    "//components/policy/test_support",
    "//components/prefs",
    "//components/signin/public/identity_manager:test_support",
    "//components/user_manager",
    "//content/test:test_support",
    "//google_apis",
    "//net",
    "//services/network:test_support",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//testing/gmock",
  ]

  if (enable_dice_support) {
    sources += [ "cloud/user_policy_signin_service_browsertest.cc" ]
    deps += [ "//chrome/browser/ui/webui/signin" ]
  }

  if (enable_extensions_core) {
    sources += [ "extension_policy_browsertest.cc" ]

    deps += [
      "//chrome/browser/extensions",
      "//chrome/browser/extensions:test_support",
      "//extensions/browser:crx_installer",
      "//extensions/browser/forced_extensions",
    ]

    if (enable_extensions) {
      deps += [
        "//chrome/browser/web_applications:web_applications_test_support",
        "//components/webapps/browser",
      ]
    }
  }

  if (is_linux || is_mac || is_win) {
    sources += [ "test/audio_sandbox_enabled_browsertest.cc" ]
  }

  if (is_mac) {
    sources += [
      "cloud/chrome_browser_cloud_management_browsertest_mac_util.h",
      "cloud/chrome_browser_cloud_management_browsertest_mac_util.mm",
      "test/ad_hoc_code_signing_for_pwas_enabled_mac_browsertest.mm",
    ]
  }

  if (is_win || is_linux) {
    sources += [ "test/network_service_sandbox_enabled_browsertest.cc" ]
  }

  sources += [ "cloud/component_cloud_policy_browsertest.cc" ]

  deps += [
    "//chrome/browser/ui",
    "//chrome/test:test_support",
  ]

  sources += [
    "cloud/chrome_browser_cloud_management_browsertest_delegate_desktop.cc",
    "cloud/chrome_browser_cloud_management_browsertest_delegate_desktop.h",
    "test/hardware_acceleration_mode_enabled_browsertest.cc",

    # Chrome OS does not support this policy.
    "test/native_messaging_policy_browsertest.cc",
    "test/swiftshader_enabled_browsertest.cc",
  ]

  if (is_mac || is_win || is_linux) {
    # Welcome and What's New pages that are controlled by the promotional
    # tabs policy are win/mac/linux only.
    sources += [ "test/promotional_tabs_enabled_policy_browsertest.cc" ]

    deps += [
      "//chrome/browser/prefs:util",
      "//chrome/browser/ui/webui/whats_new",
      "//chrome/common:version_header",
    ]
  }

  if (is_win || is_linux || is_chromeos) {
    sources += [ "test/full_screen_allowed_policy_browsertest.cc" ]

    if (enable_extensions) {
      deps += [ "//chrome/browser/apps/app_service" ]
    }
  }

  sources += [
    "cloud/chrome_browser_cloud_management_browsertest.cc",
    "cloud/chrome_browser_cloud_management_browsertest_delegate.h",
  ]

  deps += [ "//components/signin/public/identity_manager" ]

  if (is_linux) {
    sources += [ "test/out_of_process_system_dns_resolution_browsertest.cc" ]
  }
}

source_set("unit_tests") {
  testonly = true

  sources = []

  deps = []
}
