# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/metrics/generate_expired_histograms_array.gni")

source_set("metrics") {
  sources = [
    "accessibility_state_provider.h",
    "cached_metrics_profile.h",
    "network_quality_estimator_provider_impl.h",
    "ukm_background_recorder_service.h",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//components/metrics",
    "//components/metrics:net",
    "//services/metrics/public/cpp:metrics_cpp",
    "//services/network/public/cpp",
  ]
}

source_set("test_support") {
  testonly = true
  sources = [
    "testing/metrics_consent_override.cc",
    "testing/metrics_consent_override.h",
    "testing/metrics_reporting_pref_helper.cc",
    "testing/metrics_reporting_pref_helper.h",
  ]

  deps = [
    "//base",
    "//chrome/browser",
    "//chrome/browser/sync",
    "//chrome/browser/sync/test/integration:sync_integration_test_support",
    "//components/metrics_services_manager",
    "//components/signin/public/identity_manager",
    "//components/sync:test_support",
    "//third_party/metrics_proto",
  ]
}

generate_expired_histograms_array("expired_histograms_array") {
  namespace = "chrome_metrics"
  header_filename = "expired_histograms_array.h"
  major_branch_date_filepath = "//chrome/MAJOR_BRANCH_DATE"
  milestone_filepath = "//chrome/VERSION"
}
