# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true

  public = [
    "device_trust_browsertest_base.h",
    "device_trust_management_mixin.h",
    "test_constants.h",
  ]

  sources = [
    "device_trust_browsertest_base.cc",
    "device_trust_management_mixin.cc",
    "test_constants.cc",
  ]

  public_deps = [
    "//chrome/browser/enterprise/connectors/device_trust/common",
    "//chrome/browser/enterprise/test:test_support",
  ]

  deps = [
    "//chrome/browser/enterprise/connectors/device_trust:features",
    "//chrome/browser/profiles:profile",
    "//components/device_signals/core/browser",
    "//components/policy:policy_code_generate",
    "//components/prefs",
  ]

  if (is_win || is_mac || is_linux) {
    public += [ "device_trust_test_environment.h" ]
    sources += [ "device_trust_test_environment.cc" ]

    public_deps += [
      "//base",
      "//chrome/browser/enterprise/connectors/device_trust/key_management/core/network",
    ]

    deps += [
      "//chrome/browser/enterprise/connectors/device_trust/key_management/core/persistence",
      "//chrome/browser/enterprise/connectors/device_trust/key_management/core/persistence:test_support",
      "//chrome/browser/enterprise/connectors/device_trust/key_management/installer:elevated_rotation",
    ]
  }
}
