# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")

source_set("public") {
  sources = [
    "client_version_info.h",
    "data_sharing_network_loader.cc",
    "data_sharing_network_loader.h",
    "data_sharing_network_utils.h",
    "data_sharing_sdk_delegate.h",
    "data_sharing_service.h",
    "data_sharing_ui_delegate.h",
    "share_url_interception_context.cc",
    "share_url_interception_context.h",
  ]

  public_deps = [
    ":features",
    ":group_data",
    ":logger",
    "//base",
    "//components/data_sharing/migration/public",
    "//components/data_sharing/public/protocol",
    "//components/keyed_service/core",
    "//components/sync/model",
    "//net/traffic_annotation",
    "//url",
  ]
}

source_set("personal_collaboration_data") {
  sources =
      [ "personal_collaboration_data/personal_collaboration_data_service.h" ]
  public_deps = [
    "//base",
    "//components/data_sharing/public/protocol",
    "//components/keyed_service/core",
    "//components/sync/model",
  ]
}

source_set("logger") {
  sources = [
    "logger.cc",
    "logger.h",
    "logger_utils.h",
  ]
  public_deps = [ ":logger_interfaces" ]
}

mojom("logger_interfaces") {
  sources = [ "logger_common.mojom" ]
  webui_module_path = "/"
  public_deps = [ "//mojo/public/mojom/base" ]
}

static_library("features") {
  sources = [
    "features.cc",
    "features.h",
    "server_environment.h",
    "switches.h",
  ]

  public_deps = [ "//base" ]
}

static_library("group_data") {
  sources = [
    "data_sharing_utils.cc",
    "data_sharing_utils.h",
    "group_data.cc",
    "group_data.h",
  ]

  public_deps = [
    ":features",
    "//base",
    "//components/data_sharing/public/protocol",
    "//google_apis",
    "//net",
    "//url",
  ]

  deps = [ "//components/url_formatter" ]
}

source_set("unit_tests") {
  testonly = true

  visibility = [ "//components/data_sharing:unit_tests" ]

  sources = [ "data_sharing_utils_unittest.cc" ]

  deps = [
    ":group_data",
    "//base",
    "//testing/gtest",
  ]
}
