# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//device/vr/buildflags/buildflags.gni")

group("vr_perf_tests_base") {
  testonly = true
  data = [
    "./data/",
    "./desktop_runtimes/",
    "./__init__.py",
    "./shared_vr_page_state.py",
    "./vr_benchmarks.py",
    "./vr_sample_page.py",
    "./vr_story_set.py",
    "./webvr_sample_pages.py",
    "./webvr_wpr_pages.py",
    "./webxr_sample_pages.py",

    # For the ACL setup code.
    "//chrome/browser/vr/test/run_xr_browser_tests.py",
    "//chrome/test/data/xr/webvr_info/samples/",
    "//third_party/webxr_test_pages/webxr-samples/",
  ]
  data_deps = [ "//testing:run_perf_test" ]

  if (is_win) {
    if (enable_openxr) {
      data_deps += [ "//device/vr:openxr_mock" ]
    }
  }
}

group("vr_perf_tests") {
  testonly = true
  data_deps = [
    ":vr_perf_tests_base",
    "//tools/perf",
  ]
}
