# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")

component("storage_monitor") {
  sources = [
    "media_storage_util.cc",
    "media_storage_util.h",
    "removable_device_constants.cc",
    "removable_device_constants.h",
    "removable_storage_observer.h",
    "storage_info.cc",
    "storage_info.h",
    "storage_monitor.cc",
    "storage_monitor.h",
    "transient_device_ids.cc",
    "transient_device_ids.h",
  ]

  defines = [ "IS_STORAGE_MONITOR_IMPL" ]

  deps = [
    "//base",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//services/service_manager/public/cpp",
    "//ui/base",
  ]

  if (is_mac) {
    sources += [
      "storage_monitor_mac.h",
      "storage_monitor_mac.mm",
    ]
    frameworks = [
      "DiskArbitration.framework",
      "Foundation.framework",
      "UniformTypeIdentifiers.framework",
    ]
  } else if (is_linux) {
    if (use_udev) {
      sources += [
        "mtab_watcher_linux.cc",
        "mtab_watcher_linux.h",
        "storage_monitor_linux.cc",
        "storage_monitor_linux.h",
      ]
    } else {
      sources += [ "storage_monitor_dummy.cc" ]
    }
  }

  if (use_udev) {
    if (is_linux || is_chromeos) {
      sources += [
        "udev_util_linux.cc",
        "udev_util_linux.h",
      ]
    }
    deps += [ "//device/udev_linux" ]
  }
}

static_library("test_support") {
  testonly = true
  sources = [
    "mock_removable_storage_observer.cc",
    "mock_removable_storage_observer.h",
    "test_storage_monitor.cc",
    "test_storage_monitor.h",
  ]

  public_deps = [
    ":storage_monitor",
    "//base",
    "//content/public/browser",
  ]

  deps = []
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "media_storage_util_unittest.cc",
    "storage_info_unittest.cc",
    "storage_monitor_unittest.cc",
  ]

  deps = [
    ":test_support",
    "//base/test:test_support",
    "//content/test:test_support",
    "//testing/gtest",
  ]

  if (is_mac) {
    sources += [ "storage_monitor_mac_unittest.mm" ]
    frameworks = [ "UniformTypeIdentifiers.framework" ]
  }

  if (is_linux) {
    if (use_udev) {
      sources += [ "storage_monitor_linux_unittest.cc" ]
    }
  }
}
