# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//device/vr/buildflags/buildflags.gni")

assert(enable_vr)

source_set("test_support") {
  sources = [
    "xr_test_hook_wrapper.cc",
    "xr_test_hook_wrapper.h",
  ]

  deps = [
    "//base",
    "//device/vr:vr_test_hook",
    "//device/vr/public/mojom/test:test_mojom",
  ]
}
