// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b647082c6fef5f2e54796c62678d8b3117d7817a$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_browser.h"
#include "include/capi/cef_browser_capi_versions.h"
#include "include/cef_client.h"
#include "include/capi/cef_client_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 999999.
// This class may be instantiated and accessed DLL-side only.
class CefVimbrowserElementActivationCallback_999999_CToCpp
    : public CefCToCppRefCounted<CefVimbrowserElementActivationCallback_999999_CToCpp, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_999999_t> {
 public:
  CefVimbrowserElementActivationCallback_999999_CToCpp();
  virtual ~CefVimbrowserElementActivationCallback_999999_CToCpp();

  // CefVimbrowserElementActivationCallback methods.
  void OnComplete(int result, int match_count) override;
};

constexpr auto CefVimbrowserElementActivationCallbackCToCpp_Wrap = CefVimbrowserElementActivationCallback_999999_CToCpp::Wrap;
constexpr auto CefVimbrowserElementActivationCallbackCToCpp_Unwrap = CefVimbrowserElementActivationCallback_999999_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK_CTOCPP_H_
