// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=196d8f9688949896d36145e78c52293bbdc6f6a2$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/ctocpp/vimbrowser_element_activation_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 999999 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefVimbrowserElementActivationCallback_999999_CToCpp::OnComplete(int result, int match_count) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_complete) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->on_complete(_struct,
      result,
      match_count);
}

// CONSTRUCTOR FOR VERSION 999999 - Do not edit by hand.

CefVimbrowserElementActivationCallback_999999_CToCpp::CefVimbrowserElementActivationCallback_999999_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 999999) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 999999 - Do not edit by hand.

CefVimbrowserElementActivationCallback_999999_CToCpp::~CefVimbrowserElementActivationCallback_999999_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_vimbrowser_element_activation_callback_999999_t* CefCToCppRefCounted<CefVimbrowserElementActivationCallback_999999_CToCpp, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_999999_t>::UnwrapDerived(CefWrapperType type, CefVimbrowserElementActivationCallback* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefVimbrowserElementActivationCallback_999999_CToCpp, CefVimbrowserElementActivationCallback, cef_vimbrowser_element_activation_callback_999999_t>::kWrapperType = WT_VIMBROWSER_ELEMENT_ACTIVATION_CALLBACK;
