# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//pdf/features.gni")

static_library("child") {
  sources = []

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = []
  data_deps = []

  if (enable_pdf) {
    sources += [
      "pdf_child_init.cc",
      "pdf_child_init.h",
    ]
    deps += [
      "//base",
      "//content/public/child",
      "//content/public/common",
      "//pdf:buildflags",
      "//sandbox/policy",
    ]
  }
}
