# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/sanitizers/sanitizers.gni")
import("//build/config/zip.gni")
import("//chrome/updater/branding.gni")
import("//components/crx_file/crx3.gni")

copy("test_installer") {
  testonly = true
  sources = [ "test_app_setup.sh" ]
  outputs = [ "$root_build_dir/test_installer/{{source_file_part}}" ]
}

template("test_app_installer") {
  testonly = true
  app_name = target_name
  script_target = "test_script_" + app_name
  copy(script_target) {
    sources = [ invoker.script ]
    outputs =
        [ "$target_gen_dir/" + app_name + "/crx_contents/" + invoker.script ]
  }
  install_target = "install_script_" + app_name
  action(install_target) {
    script = "generate_install_script.py"
    inputs = [ script ]
    outputs = [ "$target_gen_dir/" + app_name + "/crx_contents/.install" ]
    args = [
      "--command",
      invoker.script,
      "--app",
      invoker.app,
      "--company",
      updater_company_short_name,
      "--version",
      invoker.version,
      "--output",
      rebase_path(outputs[0], root_build_dir),
    ]
  }

  crx3("test_installer_" + app_name) {
    base_dir = "$target_gen_dir/" + app_name + "/crx_contents/"
    key = "//chrome/updater/test/data/selfupdate_test_key.der"
    inputs = get_target_outputs(":" + script_target) +
             get_target_outputs(":" + install_target)
    output =
        "$root_build_dir/test_installer/test_installer_" + app_name + ".crx3"
    deps = [
      ":" + script_target,
      ":" + install_target,
    ]
  }
}

test_app_installer("test1_v1") {
  app = "test1"
  version = "1.0.0.0"
  script = "test_app_setup.sh"
}
test_app_installer("test1_v2") {
  app = "test1"
  version = "2.0.0.0"
  script = "test_app_setup.sh"
}
test_app_installer("test2_v1") {
  app = "test2"
  version = "100.0.0.0"
  script = "test_app_setup.sh"
}
test_app_installer("test2_v2") {
  app = "test2"
  version = "101.0.0.0"
  script = "test_app_setup.sh"
}
test_app_installer("test3_v1") {
  app = "test3"
  version = "1.0"
  script = "test_app_setup.sh"
}
test_app_installer("test3_v2") {
  app = "test3"
  version = "1.1"
  script = "test_app_setup.sh"
}

group("app_installers") {
  testonly = true

  data_deps = [
    ":test_installer",
    ":test_installer_test1_v1",
    ":test_installer_test1_v2",
    ":test_installer_test2_v1",
    ":test_installer_test2_v2",
    ":test_installer_test3_v1",
    ":test_installer_test3_v2",
  ]
}
