# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("collaboration") {
  sources = [
    "collaboration_service_factory.cc",
    "collaboration_service_factory.h",
    "delegate_factory.h",
  ]
  public_deps = [ "//chrome/browser/profiles:profile" ]
  deps = [
    "//base",
    "//chrome/browser/data_sharing",
    "//chrome/browser/signin",
    "//chrome/browser/tab_group_sync:factories",
    "//components/collaboration/internal:core_internal",
    "//components/data_sharing/public:features",
    "//content/public/browser",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "collaboration_service_factory_unittest.cc" ]
  deps = [
    ":collaboration",
    "//base/test:test_support",
    "//chrome/browser/sync",
    "//chrome/browser/sync:factories",
    "//chrome/test:test_support",
    "//components/collaboration/internal:core_internal",
    "//components/data_sharing/public:features",
    "//components/sync:test_support",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
