# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/browser/buildflags.gni")

source_set("feature_engagement") {
  sources = [ "tracker_factory.h" ]
  public_deps = [
    "//chrome/browser/profiles",
    "//components/feature_engagement/public",
  ]
}

source_set("impl") {
  sources = [ "tracker_factory.cc" ]
  deps = [
    ":feature_engagement",
    "//base",
    "//chrome/common:constants",
    "//chrome/common:non_code_constants",
    "//components/prefs",
    "//content/public/browser",
  ]

  deps += [ "//chrome/browser/user_education" ]

  public_deps = [
    "//chrome/browser/profiles",
    "//components/feature_engagement/public",
  ]
}
