# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

component("common") {
  sources = [
    "user_type.cc",
    "user_type.h",
  ]

  defines = [ "IS_USER_MANAGER_COMMON_IMPL" ]

  deps = [ "//base" ]
}

component("user_manager") {
  sources = [
    "multi_user/multi_user_sign_in_policy.cc",
    "multi_user/multi_user_sign_in_policy.h",
    "user_manager_export.h",
    "user_manager_pref_names.h",
    "user_names.cc",
    "user_names.h",
  ]

  public_deps = [
    ":common",
    "//base",
    "//components/account_id",
    "//components/prefs",
    "//google_apis",
    "//ui/gfx",
  ]

  deps = [
    "//components/crash/core/common",
    "//google_apis",
  ]

  defines = [ "USER_MANAGER_IMPLEMENTATION" ]
}
