# Copyright 2017 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("core") {
  sources = [
    "fail_state.cc",
    "fail_state.h",
    "filtered_offline_item_observer.cc",
    "filtered_offline_item_observer.h",
    "launch_location.h",
    "offline_content_aggregator.cc",
    "offline_content_aggregator.h",
    "offline_content_provider.cc",
    "offline_content_provider.h",
    "offline_item.cc",
    "offline_item.h",
    "offline_item_filter.h",
    "offline_item_state.h",
    "open_params.cc",
    "open_params.h",
    "pending_state.h",
    "rename_result.h",
    "throttled_offline_content_provider.cc",
    "throttled_offline_content_provider.h",
    "update_delta.cc",
    "update_delta.h",
  ]

  public_deps = [
    "//base",
    "//components/download/public/common:public",
    "//components/keyed_service/core",
    "//ui/gfx",
    "//url",
  ]

  deps = [
    "utilities",
    "//ui/gfx/geometry",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "filtered_offline_item_observer_unittest.cc",
    "offline_content_aggregator_unittest.cc",
    "throttled_offline_content_provider_unittest.cc",
  ]

  deps = [
    ":core",
    "utilities:unit_tests",
    "//base/test:test_support",
    "//components/offline_items_collection/core/test_support",
  ]
}
