# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")

# Concrete implementation of Publisher interface.
# Importantly this must not be depended on by app_service.
# The the dependency must be injected at earlier stage on runtime.
source_set("publishers") {
  sources = [
    "app_publisher.cc",
    "app_publisher.h",
    "extension_apps.cc",
    "extension_apps.h",
    "extension_apps_base.cc",
    "extension_apps_base.h",
    "extension_apps_enable_flow.cc",
    "extension_apps_enable_flow.h",
    "extension_apps_util.cc",
    "extension_apps_util.h",
    "publisher_host_factory_impl.cc",
    "publisher_host_factory_impl.h",
    "publisher_host_impl.cc",
    "publisher_host_impl.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = [
    "//base",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/apps/app_service",
    "//chrome/browser/apps/app_service/app_icon",
    "//chrome/browser/extensions",
    "//chrome/browser/prefs",
    "//chrome/browser/ui",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/extensions:extension_enable_flow_delegate",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications/app_service",
  ]

  # TODO(crbug.com/441649482): circular dependency to support concrete
  # publisher implementation. Resolve the dependency.
  allow_circular_includes_from = [
    # app_publisher is referred as a skeleton implementation.
    "//chrome/browser/web_applications/app_service",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "app_publisher_unittest.cc",
    "publisher_unittest.cc",
  ]

  deps = [
    ":publishers",
    "//base",
    "//chrome/app:branded_strings",
    "//chrome/browser/apps/app_service",
    "//chrome/browser/apps/app_service:test_support",
    "//chrome/browser/extensions",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications:web_applications_test_support",
    "//chrome/browser/web_applications/mojom:mojom_web_apps_enum",
    "//chrome/common:chrome_features",
    "//chrome/test:test_support",
    "//components/account_id",
    "//components/app_constants",
    "//components/services/app_service",
    "//components/services/app_service/public/cpp:app_types",
    "//content/test:test_support",
    "//extensions/browser",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//url",
  ]
}
