# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("browser") {
  sources = [
    "web_signin_tracker.cc",
    "web_signin_tracker.h",
  ]

  deps = [
    "//components/signin/core/browser",
    "//components/signin/public/base",
    "//components/signin/public/base:signin_buildflags",
    "//components/signin/public/identity_manager",
    "//google_apis",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "web_signin_tracker_unittest.cc" ]

  deps = [
    ":browser",
    "//base",
    "//base/test:test_support",
    "//components/signin/core/browser",
    "//components/signin/public/base",
    "//components/signin/public/base:test_support",
    "//components/signin/public/identity_manager",
    "//components/signin/public/identity_manager:test_support",
    "//components/sync_preferences:test_support",
    "//google_apis",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
