#!/usr/bin/perl

sub sockaddr_un_linux {
    my ($path) = @_;
    die "vimbrowser-ipc: socket path too long: $path\n" if length($path) >= 108;
    return pack("S Z108", 1, $path);
}

if (@ARGV && $ARGV[0] eq "screenshot") {
    my $helper = $0;
    $helper =~ s{/[^/]*$}{/vimbrowser-ipc-screenshot};
    $helper = "./vimbrowser-ipc-screenshot" if $helper eq $0;
    exec $helper, @ARGV;
    die "vimbrowser-ipc: exec $helper: $!\n";
}

sub default_socket_path {
    return "$ENV{VIMBROWSER_PROFILE_DIR}/ipc.sock"
        if exists $ENV{VIMBROWSER_PROFILE_DIR} && length $ENV{VIMBROWSER_PROFILE_DIR};

    my $wrapper_profile_socket = "/home/yeyito/.runtime/vimbrowser-yeyito/ipc.sock";
    return $wrapper_profile_socket if -e $wrapper_profile_socket;

    return "$ENV{XDG_STATE_HOME}/vimbrowser/ipc.sock"
        if exists $ENV{XDG_STATE_HOME} && length $ENV{XDG_STATE_HOME};
    return "$ENV{HOME}/.local/state/vimbrowser/ipc.sock"
        if exists $ENV{HOME} && length $ENV{HOME};
    return "/tmp/vimbrowser/ipc.sock";
}

my $path = exists $ENV{VIMBROWSER_IPC} && length $ENV{VIMBROWSER_IPC}
    ? $ENV{VIMBROWSER_IPC}
    : default_socket_path();
my $command = @ARGV == 1 ? $ARGV[0] : (@ARGV ? join(" ", @ARGV) : "status");

socket(my $sock, 1, 1, 0)
    or die "vimbrowser-ipc: socket: $!\n";
connect($sock, sockaddr_un_linux($path))
    or die "vimbrowser-ipc: connect $path: $!\n";

my $request = "$command\n";
my $offset = 0;
while ($offset < length($request)) {
    my $written = syswrite($sock, $request, length($request) - $offset, $offset);
    die "vimbrowser-ipc: write: $!\n" unless defined $written;
    $offset += $written;
}

my $buffer;
while (1) {
    my $read = sysread($sock, $buffer, 262144);
    die "vimbrowser-ipc: recv: $!\n" unless defined $read;
    last if $read == 0;
    $offset = 0;
    while ($offset < $read) {
        my $written = syswrite(STDOUT, $buffer, $read - $offset, $offset);
        die "vimbrowser-ipc: write: $!\n" unless defined $written;
        $offset += $written;
    }
}
exit 0;
