# Copyright 2015 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ==============================================================================
# TEST SETUP
# ==============================================================================

import("//build/config/chromeos/args.gni")
import("//build/config/chromeos/ui_mode.gni")
import("//build/config/devtools.gni")
import("//build/config/gclient_args.gni")
import("//build/config/rts.gni")
import("//build/rust/rust_static_library.gni")
import("//build_overrides/build.gni")

declare_args() {
  # Some component repos (e.g. ANGLE) import //testing but do not have
  # "location_tags.json", and so we don't want to try and upload the tags
  # for their tests.
  # And, some build configs may simply turn off generation altogether.
  tests_have_location_tags = generate_location_tags

  # Build individual_fuzztest_wrapper if use_fuzztest_wrapper is set.
  # Some projects doesn't have //base and cannot build
  # individual_fuzztest_wrapper.
  use_fuzztest_wrapper = true
}

# On Fuchsia, the test executable has a suffix and is a dependency of the
# common |target_name| target. For `visibility`, the executable must be
# specified. Cross-platform targets that include `test` targets in their
# visibility lists, add `${exec_target_suffix}` immediately after the test
# target name. This is not necessary when the target is a `source_set`.
exec_target_suffix = ""

if (is_chromeos && is_chromeos_device) {
  import("//build/config/chromeos/rules.gni")
  import("//build/config/sanitizers/sanitizers.gni")
  import("//build/util/generate_wrapper.gni")
} else {
  import("//build/config/sanitizers/sanitizers.gni")
  import("//build/util/generate_wrapper.gni")
}

# This template represents the core common functionality of a test target
# on each platform. It includes:
# * the ability to generate a rust library that includes all .rs files found
#   in sources and depends on that from the test target.
# * the ability to recognize any declare fuzztests and build runners for them.
template("mixed_test") {
  assert(defined(invoker.target_type) && invoker.target_type != "")

  # The crate_root variable would transform the target into a Rust binary
  # which is incorrect. To not use a generated crate root set:
  # ```
  # test_crate_root = "path/to/root.rs"
  # ```
  assert(!defined(invoker.crate_root))

  _rs_vars = [
    "sources",  # We split this list into two.
    "crate_name",  # Android test template overrides the crate name.
  ]

  if (defined(invoker.sources)) {
    _rs_sources = filter_include(invoker.sources, [ "*.rs" ])
    _cc_sources = filter_exclude(invoker.sources, [ "*.rs" ])
  } else {
    _rs_sources = []
    _cc_sources = []
  }

  if (_rs_sources != []) {
    # Note: as a weak convention, __ is usually used before a suffix for
    # internally-generated targets. However, rust_target requires a strict
    # snake_case name.
    if (defined(invoker.crate_name)) {
      _rust_target_name = "${invoker.crate_name}_rust_objects"
    } else {
      _rust_target_name = "${target_name}_rust_objects"
    }

    # We could automatically add `deps += [ "//testing/rust_gtest_interop" ]`
    # if `rs_sources` is non-empty. But we don't automatically provide
    # //testing/gtest either so it would be asymmetric and could break in that
    # case. So, we act instead as if //testing/rust_gtest_interop is part of
    # the //testing/gtest dependency. If you add one, and have `rs_sources`
    # listed, you get both.
    _gtest_is_in_deps = false
    if (defined(invoker.deps) && invoker.deps != []) {
      foreach(dep, invoker.deps) {
        if (get_label_info(dep, "label_no_toolchain") ==
            "//testing/gtest:gtest") {
          _gtest_is_in_deps = true
        }
      }
    }

    # TODO(danakj): This could be a rust_source_set perhaps, the point being
    # that we need to link in all the .o object files inside the library,
    # instead of dropping unreachable ones during linking (which would drop the
    # tests). Alternatively we could use a special name suffix or other similar
    # trick perhaps to ensure that all object files are linked in here.
    rust_static_library(_rust_target_name) {
      forward_variables_from(invoker,
                             TESTONLY_AND_VISIBILITY + [
                                   "allow_unsafe",
                                   "deps",
                                   "generate_crate_root",
                                   "public_deps",
                                 ])
      configs += [ "//build/rust:test" ]
      if (defined(invoker.test_crate_root)) {
        crate_root = invoker.test_crate_root
      } else {
        generate_crate_root = true
      }
      sources = _rs_sources
      is_gtest_unittests = true

      if (_gtest_is_in_deps) {
        deps += [ "//testing/rust_gtest_interop" ]
      }
    }
  } else {
    not_needed(invoker, _rs_vars)
  }

  if (invoker.target_type == "shared_library_with_jni") {
    # Needed for shared_library_with_jni. Keeping this import guarded so
    # that projects who import //testing but not //third_party/jni_zero
    # don't have issues.
    import("//third_party/jni_zero/jni_zero.gni")
  }

  _building_fuzztest_fuzzer =
      defined(invoker.fuzztests) && use_fuzzing_engine && (is_linux || is_mac)

  # Fuzz tests are small fuzzers that do not require particularly-powerful
  # machines to run, so we do not build them when `high_end_fuzzer_targets`
  # is true and we are building fuzztests in fuzzing mode.
  if (_building_fuzztest_fuzzer && high_end_fuzzer_targets) {
    not_needed(invoker, "*")
    not_needed("*")

    # We still want a reachable target, so make it a no-op empty group. This
    # will let the fuzzer builders crawl the build graph and invoke ninja in
    # the same way regardless of GN args.
    group(target_name) {
    }
  } else {
    target(invoker.target_type, target_name) {
      forward_variables_from(invoker,
                             "*",
                             TESTONLY_AND_VISIBILITY + _rs_vars + [
                                   "fuzztests",
                                   "fuzztest_additional_args",
                                   "libfuzzer_options",
                                   "centipede_options",
                                   "asan_options",
                                   "msan_options",
                                   "ubsan_options",
                                   "environment_variables",
                                   "grammar_options",
                                 ])
      forward_variables_from(invoker, TESTONLY_AND_VISIBILITY)
      sources = _cc_sources
      if (!defined(deps)) {
        deps = []
      }
      if (!defined(ldflags)) {
        ldflags = []
      }

      if (_rs_sources != []) {
        deps += [ ":${_rust_target_name}" ]
      }
      if (defined(invoker.fuzztests)) {
        deps += [
          "//third_party/fuzztest",

          # The following target contains a static initializer which
          # will ensure that the code in base/test:test_support
          # ends up calling through to fuzztest::InitFuzzTest.
          "//testing/libfuzzer:confirm_fuzztest_init",
        ]
      }
    }
  }

  if (_building_fuzztest_fuzzer && !high_end_fuzzer_targets) {
    # This test contains fuzztests. We want to package them up in a way
    # which ClusterFuzz knows how to extract. We need to:
    # 1) make an executable for each individual fuzz test;
    # 2) check that the fuzztests variable is correct.
    # At present, all this is likely to work only if invoker.target_type
    # is 'executable', since we generate a wrapper script that assumes so.
    # At the moment, we aim to fuzz these fuzztests only on Linux so that's
    # fine. In future we may need to broaden this.

    # It makes no sense to have an empty fuzztests variable, let's forbid it.
    assert(invoker.fuzztests != [])
    if (defined(invoker.output_name)) {
      _output_name = invoker.output_name
    } else {
      _output_name = target_name
    }

    _fuzzer_binary_extension = ""

    # This will be the actual name of the fuzzer binary generated by
    # `target_name`.
    _fuzzer_binary_name = _output_name + _fuzzer_binary_extension
    _fuzztest_target_name = target_name

    # Additional command-line arguments passed to fuzzer executables, common to
    # all fuzz tests in this executable.
    _common_fuzzer_args = [ "--corpus_database=" ]

    if (defined(invoker.fuzztest_additional_args)) {
      _common_fuzzer_args += invoker.fuzztest_additional_args
    }

    # Confirming that the "fuzztests =" directive is correct can only
    # be done on builds where we can confidently run the fuzzing binary.
    # Let's be conservative about that -- so long as any failures are
    # spotted by at least one CI bot we should be good.
    confirm_fuzztest_contents = is_asan || !using_sanitizer

    if (confirm_fuzztest_contents) {
      # Confirm that the fuzztests GN variable matches with the
      # actual fuzztests in the binary. The output of this action is unused.
      # It just exists to fail the build if there's an error.
      # We only do this on Linux, and not for any sanitizers other than
      # ASAN, because that's specific for CI to show problems and there
      # may be unknown problems running the fuzztest binary on other
      # platforms.
      _fuzztest_check_action = target_name + "__fuzztest_check"
      action(_fuzztest_check_action) {
        deps = [ ":" + _fuzztest_target_name ]
        testonly = true
        script = "//testing/libfuzzer/confirm_fuzztests.py"
        _output_name = "$target_gen_dir/${target_name}__checked.txt"
        outputs = [ _output_name ]

        args = [
                 "--executable",
                 rebase_path(
                     get_label_info(_fuzztest_target_name, "root_out_dir") +
                     "/" + _fuzzer_binary_name),
                 "--output",
                 rebase_path(_output_name),
                 "--fuzztests",
               ] + invoker.fuzztests
      }
    }

    # Make a wrapper executable for each individual fuzz test
    if (use_fuzztest_wrapper) {
      foreach(fuzztest_unit, invoker.fuzztests) {
        _fuzzer_name = target_name + "_" +
                       string_replace(fuzztest_unit, ".", "_") + "_fuzzer"

        # We generate an actual executable because currently our fuzz
        # builder recipes use `gn refs --type=executable` to find things
        # to build. Otherwise we could use generate_wrapper or equivalent
        # to make a python script. We could alter the recipe, or rearrange
        # deps arragenements so that some other executable depends on these
        # scripts, but that seems worse. The executable might be more cross-
        # platform too.
        _fuzztest_generate_fuzzer = _fuzzer_name + "__generate"

        generated_file(_fuzztest_generate_fuzzer + "_constants") {
          outputs = [ "$target_gen_dir/$target_name/constants.cpp" ]

          _fuzzer_args = _common_fuzzer_args + [ "--fuzz=${fuzztest_unit}" ]

          fuzzer_args_joined = string_join(" ", _fuzzer_args)

          NEWLINE = "$0x0A"

          contents =
              "const char* kFuzzerArgs = \"${fuzzer_args_joined}\";" + NEWLINE +
              "const char* kFuzzerBinary = \"${_fuzzer_binary_name}\";" +
              NEWLINE
        }

        _additional_fuzz_deps = []
        gen_fuzzer_config_args = []

        if (defined(invoker.libfuzzer_options)) {
          gen_fuzzer_config_args += [ "--libfuzzer_options" ]
          gen_fuzzer_config_args += invoker.libfuzzer_options
        }

        if (defined(invoker.centipede_options)) {
          gen_fuzzer_config_args += [ "--centipede_options" ]
          gen_fuzzer_config_args += invoker.centipede_options
        }

        if (defined(invoker.asan_options)) {
          gen_fuzzer_config_args += [ "--asan_options" ]
          gen_fuzzer_config_args += invoker.asan_options
        }

        if (defined(invoker.msan_options)) {
          gen_fuzzer_config_args += [ "--msan_options" ]
          gen_fuzzer_config_args += invoker.msan_options
        }

        if (defined(invoker.ubsan_options)) {
          gen_fuzzer_config_args += [ "--ubsan_options" ]
          gen_fuzzer_config_args += invoker.ubsan_options
        }

        if (defined(invoker.environment_variables)) {
          gen_fuzzer_config_args += [ "--environment_variables" ]
          gen_fuzzer_config_args += invoker.environment_variables
        }

        if (defined(invoker.grammar_options)) {
          gen_fuzzer_config_args += [ "--grammar_options" ]
          gen_fuzzer_config_args += invoker.grammar_options
        }

        if (gen_fuzzer_config_args != []) {
          _config_file_name = _fuzzer_name + ".options"
          _additional_fuzz_deps += [ ":" + _config_file_name ]

          # Generate .options file.
          action(_config_file_name) {
            script = "//testing/libfuzzer/gen_fuzzer_config.py"
            args = [
              "--config",
              rebase_path("$root_build_dir/" + _config_file_name,
                          root_build_dir),
            ]

            args += gen_fuzzer_config_args

            outputs = [ "$root_build_dir/$_config_file_name" ]
          }
        }

        _fuzzer_target_name = target_name
        executable(_fuzztest_generate_fuzzer) {
          testonly = true
          data_deps = [
                        ":" + _fuzztest_target_name,
                        ":" + _fuzzer_target_name,
                      ] + _additional_fuzz_deps
          deps = [
            "//testing/libfuzzer:individual_fuzztest_wrapper",
            ":" + _fuzztest_generate_fuzzer + "_constants",
          ]
          if (confirm_fuzztest_contents) {
            deps += [ ":" + _fuzztest_check_action ]
          }
          output_name = _fuzzer_name
          sources =
              get_target_outputs(":" + _fuzztest_generate_fuzzer + "_constants")
          write_runtime_deps = "$root_build_dir/${_fuzzer_name}.runtime_deps"
        }
      }
    } else {
      not_needed([
                   "_common_fuzzer_args",
                   "_fuzzer_binary_name",
                   "_fuzztest_target_name",
                 ])
    }
  }
}

# Define a test as an executable (or apk on Android) with the "testonly" flag
# set.
# Variable:
#   use_xvfb: (optional) whether to run the executable under Xvfb.
#   use_raw_android_executable: Use executable() rather than android_apk().
#   use_native_activity: Test implements ANativeActivity_onCreate().
#   test_runner_shard: (Fuchsia, optional): for CFv2 tests, use the given test
#      runner shard rather than the default shard for the ELF runner when
#      assembling the test component. This is useful, for example, to use the
#      elf_test_ambient_exec_runner for tests that require
#      job_policy_ambient_mark_vmo_exec.
#   fuchsia_package_deps: (Fuchsia, optional) List of fuchsia_component()
#      targets that this test package contains.
#   is_xctest: (iOS, optional) whether to build the executable as XCTest.
#      Similar to the GN arg 'enable_run_ios_unittests_with_xctest' but
#      for build targets.
#   allow_cleartext_traffic: (Android, optional) whether to allow cleartext
#      network requests during the test.
#   fuzztests: a list of instances of the FUZZ_TEST macro to
#      include fuzzing tests alongside unit tests. This introduces an
#      extra dependency and also creates additional metadata so that our
#      fuzzing infrastructure can find and run such tests.
#      This should be a list of the test names, for example
#      fuzztests = [ "MyTestClass.MyTestName" ]
#   fuzztest_additional_args: additional arguments to be forwarded to fuzztest.
template("test") {
  # Ensures a test filter file exists and if not, creates a dummy file.
  # The Regression Test Selection (rts) flag is passed in mb.py and used
  # to filter out test cases. Flag ensures that a file exists.
  if (use_rts) {
    action("${target_name}__rts_filters") {
      script = "//build/add_rts_filters.py"
      rts_file = "${root_build_dir}/gen/rts/${invoker.target_name}.filter"
      args = [ rebase_path(rts_file, root_build_dir) ]
      outputs = [ rts_file ]
    }
  }
  testonly = true
  assert(!defined(invoker.is_xctest) || !invoker.is_xctest,
         "is_xctest can be set only for iOS builds")

  assert(!defined(invoker.allow_cleartext_traffic),
         "allow_cleartext_traffic can be set only for Android tests")

  if (is_chromeos && cros_board != "") {
    assert(!defined(invoker.use_xvfb) || !invoker.use_xvfb)

    # Building for a cros board (ie: not linux-chromeos).

    _gen_runner_target = "${target_name}__runner"
    _runtime_deps_file =
        "$root_out_dir/gen.runtime/" + get_label_info(target_name, "dir") +
        "/" + get_label_info(target_name, "name") + ".runtime_deps"

    if (is_skylab && (defined(tast_attr_expr) || defined(tast_tests) ||
                      defined(tast_disabled_tests))) {
      generate_skylab_tast_filter(_gen_runner_target) {
      }
    } else {
      generate_runner_script(_gen_runner_target) {
        generated_script = "$root_build_dir/bin/run_" + invoker.target_name
        test_exe = invoker.target_name
        runtime_deps_file = _runtime_deps_file

        if (tests_have_location_tags) {
          data = [ "//testing/location_tags.json" ]
        }
        if (use_rts) {
          data_deps = [ ":${invoker.target_name}__rts_filters" ]
        }
      }
    }

    mixed_test(target_name) {
      target_type = "executable"
      forward_variables_from(invoker, "*", TESTONLY_AND_VISIBILITY)
      forward_variables_from(invoker, [ "visibility" ])
      if (!defined(deps)) {
        deps = []
      }
      if (!defined(data)) {
        data = []
      }

      # We use a special trigger script for CrOS hardware tests.
      data += [ "//testing/trigger_scripts/chromeos_device_trigger.py" ]

      write_runtime_deps = _runtime_deps_file
      data += [ _runtime_deps_file ]
      deps += [ ":$_gen_runner_target" ]

      if (!defined(data_deps)) {
        data_deps = []
      }

      data_deps += [ "//testing:test_scripts_shared" ]
      if (use_rts) {
        data_deps += [ ":${invoker.target_name}__rts_filters" ]
      }
    }
  } else {
    if (is_mac || is_win) {
      assert(!defined(invoker.use_xvfb) || !invoker.use_xvfb)
    }

    _runtime_deps_file = "$root_out_dir/${target_name}.runtime_deps"
    _executable = target_name
    _gen_runner_target = "${target_name}__runner"

    if ((is_linux || is_chromeos) && defined(invoker.use_xvfb)) {
      _use_xvfb = invoker.use_xvfb
    } else {
      _use_xvfb = false
    }

    generate_wrapper(_gen_runner_target) {
      wrapper_script = "$root_build_dir/bin/run_" + _executable

      data = []
      data_deps = [ "//testing:test_scripts_shared" ]

      if (_use_xvfb) {
        executable = "//testing/xvfb.py"
      } else {
        executable = "//testing/test_env.py"
      }
      if (tests_have_location_tags) {
        data += [ "//testing/location_tags.json" ]
      }

      executable_args = [
        "@WrappedPath(./${_executable})",
        "--test-launcher-bot-mode",
      ]
      if (is_asan) {
        executable_args += [ "--asan=1" ]
      }
      if (is_msan) {
        executable_args += [ "--msan=1" ]
      }
      if (is_tsan) {
        executable_args += [ "--tsan=1" ]
      }
      if (use_cfi_diag) {
        executable_args += [ "--cfi-diag=1" ]
      }
      if (fail_on_san_warnings) {
        executable_args += [ "--fail-san=1" ]
      }
      if (use_rts) {
        data_deps += [ ":${invoker.target_name}__rts_filters" ]
      }
    }

    mixed_test(target_name) {
      target_type = "executable"
      forward_variables_from(invoker,
                             "*",
                             TESTONLY_AND_VISIBILITY + [ "use_xvfb" ])
      forward_variables_from(invoker, [ "visibility" ])
      if (!defined(deps)) {
        deps = []
      }

      deps += [
        # Give tests the default manifest on Windows (a no-op elsewhere).
        "//build/win:default_exe_manifest",
      ]

      write_runtime_deps = _runtime_deps_file
      deps += [ ":$_gen_runner_target" ]

      if (!defined(data_deps)) {
        data_deps = []
      }

      data_deps += [ "//testing:test_scripts_shared" ]
      if (use_rts) {
        data_deps += [ ":${invoker.target_name}__rts_filters" ]
      }
    }
  }
}

# Defines a type of test that invokes a script to run, rather than
# invoking an executable.
#
# The script must implement the
# [test executable API](//docs/testing/test_executable_api.md).
#
# The template must be passed the `script` parameter, which specifies the path
# to the script to run. It may optionally be passed a `args` parameter, which
# can be used to include a list of args to be specified by default. The
# template will produce a `$root_build_dir/run_$target_name` wrapper and write
# the runtime_deps for the target to
# $root_build_dir/${target_name}.runtime_deps, as per the conventions listed in
# the [test wrapper API](//docs/testing/test_wrapper_api.md).
#
# Variables:
#   script: Path to underlying test script.
#   args: Args to the test script.
#   enable_cros_wrapper: (optional) If true, the test will get wrapped by the
#       cros_test_wrapper on ChromeOS, which will prep the device for testing.
template("script_test") {
  _enable_logdog_wrapper = false

  _enable_cros_wrapper =
      defined(invoker.enable_cros_wrapper) && invoker.enable_cros_wrapper &&
      is_chromeos && is_chromeos_device
  assert(!(_enable_logdog_wrapper && _enable_cros_wrapper),
         "The logdog and cros_test wrappers are mutually exclusive")

  if (use_rts) {
    action("${target_name}__rts_filters") {
      script = "//build/add_rts_filters.py"
      rts_file = "${root_build_dir}/gen/rts/${invoker.target_name}.filter"
      args = [ rebase_path(rts_file, root_build_dir) ]
      outputs = [ rts_file ]
    }
  }

  _shared_data = [ invoker.script ]
  if (defined(invoker.data)) {
    _shared_data += invoker.data
  }
  if (tests_have_location_tags) {
    _shared_data += [ "//testing/location_tags.json" ]
  }

  _shared_data_deps = [ "//testing:test_scripts_shared" ]
  if (defined(invoker.data_deps)) {
    _shared_data_deps += invoker.data_deps
  }
  if (use_rts) {
    _shared_data_deps += [ ":${invoker.target_name}__rts_filters" ]
  }

  _wrapped_script =
      "@WrappedPath(" + rebase_path(invoker.script, root_build_dir) + ")"
  if (_enable_logdog_wrapper) {
    logdog_wrapper_script_test(target_name) {
      testonly = true
      args = [ _wrapped_script ]
      if (defined(invoker.args)) {
        args += invoker.args
      }
      data = _shared_data
      data_deps = _shared_data_deps

      forward_variables_from(invoker,
                             "*",
                             TESTONLY_AND_VISIBILITY + [
                                   "args",
                                   "data",
                                   "data_deps",
                                   "script",
                                 ])
    }
  } else if (_enable_cros_wrapper) {
    cros_test_wrapper_script_test(target_name) {
      args = [ _wrapped_script ]
      if (defined(invoker.args)) {
        args += invoker.args
      }
      data = _shared_data
      data_deps = _shared_data_deps

      forward_variables_from(invoker,
                             "*",
                             TESTONLY_AND_VISIBILITY + [
                                   "args",
                                   "data",
                                   "data_deps",
                                   "script",
                                 ])
    }
  } else {
    generate_wrapper(target_name) {
      testonly = true
      wrapper_script = "${root_build_dir}/bin/run_${target_name}"

      executable = "//testing/test_env.py"

      executable_args = [ _wrapped_script ]
      if (defined(invoker.args)) {
        executable_args += invoker.args
      }

      data = _shared_data
      data_deps = _shared_data_deps

      forward_variables_from(invoker,
                             "*",
                             TESTONLY_AND_VISIBILITY + [
                                   "args",
                                   "data",
                                   "data_deps",
                                   "script",
                                 ])
      forward_variables_from(invoker, [ "visibility" ])

      write_runtime_deps = "${root_build_dir}/${target_name}.runtime_deps"
    }
  }
}

# Defines a test target that uses exit code for pass/fail.
template("isolated_script_test") {
  script_test(target_name) {
    forward_variables_from(invoker,
                           "*",
                           TESTONLY_AND_VISIBILITY + [
                                 "args",
                                 "data",
                                 "deps",
                                 "script",
                               ])
    forward_variables_from(invoker, [ "visibility" ])
    deps = [ "//testing:run_isolated_script_test" ]
    if (defined(invoker.deps)) {
      deps += invoker.deps
    }
    script = "//testing/scripts/run_isolated_script_test.py"
    data = [ invoker.script ]
    if (defined(invoker.data)) {
      data += invoker.data
    }
    args = [
      rebase_path(invoker.script, root_build_dir),
      "--script-type=bare",
    ]
    if (defined(invoker.args)) {
      args += invoker.args
    }
  }
}

# Test defaults.
set_defaults("test") {
  configs = default_executable_configs
}
