# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/common/features.gni")

source_set("internal") {
  sources = [
    "browser_collection.cc",
    "create_browser_window.cc",
    "global_browser_collection.cc",
    "profile_browser_collection.cc",
  ]
  deps = [
    "//base",
    "//chrome/browser:browser_process",
    "//chrome/browser:global_features",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/browser_window:create_browser_window",
    "//components/sessions:session_id",
    "//ui/base/unowned_user_data",
  ]

  sources += [
    "browser_window_features.cc",
    "browser_window_interface_iterator_non_android.cc",
    "create_browser_window_non_android.cc",
    "desktop_browser_window_capabilities.cc",
    "embedder_browser_window_features.cc",
    "global_browser_collection_platform_delegate_non_android.cc",
  ]
  public_deps = [ "//chrome/browser:browser_public_dependencies" ]

  deps += [
    "//chrome/browser:global_features",
    "//chrome/browser/actor/ui",
    "//chrome/browser/actor/ui/task_list_bubble:controller",
    "//chrome/browser/autocomplete:aim_eligibility_service",
    "//chrome/browser/collaboration",
    "//chrome/browser/contextual_tasks:ui",
    "//chrome/browser/devtools",
    "//chrome/browser/glic",
    "//chrome/browser/lens/region_search",
    "//chrome/browser/media/router:media_router_feature",
    "//chrome/browser/prefs",
    "//chrome/browser/skills:public",
    "//chrome/browser/tab_group_sync:factories",
    "//chrome/browser/ui:tab_search_feature",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/bookmarks",
    "//chrome/browser/ui/call_to_action",
    "//chrome/browser/ui/commerce",
    "//chrome/browser/ui/context_highlight",
    "//chrome/browser/ui/contextual_search",
    "//chrome/browser/ui/exclusive_access",
    "//chrome/browser/ui/extensions",
    "//chrome/browser/ui/find_bar",
    "//chrome/browser/ui/lens",
    "//chrome/browser/ui/performance_controls",
    "//chrome/browser/ui/signin",
    "//chrome/browser/ui/sync",
    "//chrome/browser/ui/tabs",
    "//chrome/browser/ui/tabs:glic",
    "//chrome/browser/ui/tabs:tab_list_bridge",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/tabs/organization",
    "//chrome/browser/ui/tabs/projects:impl",
    "//chrome/browser/ui/tabs/saved_tab_groups",
    "//chrome/browser/ui/tabs/tab_strip_api",
    "//chrome/browser/ui/tabs/tab_strip_api:impl_header",
    "//chrome/browser/ui/toasts",
    "//chrome/browser/ui/toolbar/chrome_labs",
    "//chrome/browser/ui/views/contextual_tasks",
    "//chrome/browser/ui/views/download",
    "//chrome/browser/ui/views/interaction:impl",
    "//chrome/browser/ui/views/location_bar/cookie_controls",
    "//chrome/browser/ui/views/new_tab_footer",
    "//chrome/browser/ui/views/send_tab_to_self",
    "//chrome/browser/ui/views/side_panel",
    "//chrome/browser/ui/views/tabs/projects",
    "//chrome/browser/ui/views/toolbar",
    "//chrome/browser/ui/waap:manager",
    "//chrome/browser/ui/waap:window_metrics_manager",
    "//chrome/browser/ui/web_applications",
    "//chrome/browser/ui/web_applications:launch_utils",
    "//chrome/browser/ui/webui_browser",
    "//components/breadcrumbs/core:status",
    "//components/collaboration/public",
    "//components/commerce/core:feature_list",
    "//components/data_sharing/public",
    "//components/lens:features",
    "//components/profile_metrics",
    "//components/saved_tab_groups/public",
    "//components/search",
    "//components/tabs:public",
  ]

  if (is_win || is_mac) {
    deps += [
      "//chrome/browser/ui/pdf/infobar",
      "//chrome/browser/ui/startup/default_browser_prompt/pin_infobar",
    ]

    if (enable_extensions_core) {
      deps += [ "//chrome/browser/ui/search_engines" ]
    }
  }

  if (is_win || is_mac || is_linux) {
    deps += [ "//chrome/browser/ui/views/session_restore_infobar" ]
  }

  if (use_aura) {
    deps += [ "//chrome/browser/ui:overscroll_pref_manager" ]
  }

  if (enable_extensions_core) {
    deps += [ "//chrome/browser/extensions" ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [ "browser_collection_unittest.cc" ]
  deps = [
    ":internal",
    "//chrome/browser/ui:test_support",
    "//chrome/browser/ui/browser_window",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
