# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD - style license that can be
# found in the LICENSE file.

source_set("public") {
  sources = [
    "collaboration_finder.h",
    "saved_tab_group.cc",
    "saved_tab_group.h",
    "saved_tab_group_tab.cc",
    "saved_tab_group_tab.h",
    "synthetic_field_trial_helper.cc",
    "synthetic_field_trial_helper.h",
    "tab_group_sync_metrics_logger.h",
    "tab_group_sync_service.cc",
    "tab_group_sync_service.h",
    "tab_group_sync_service_factory_helper.h",
    "types.cc",
    "types.h",
    "utils.cc",
    "utils.h",
    "versioning_message_controller.h",
  ]
  deps = [
    "//base",
    "//components/data_sharing/public:group_data",
    "//components/saved_tab_groups/proto",
    "//components/sync",
    "//components/sync_device_info",
    "//components/tab_groups",
    "//google_apis",
    "//services/metrics/public/cpp:metrics_cpp",
    "//ui/gfx",
    "//url",
  ]
  public_deps = [
    ":features",
    ":prefs",
  ]
}

source_set("features") {
  sources = [
    "features.cc",
    "features.h",
  ]
  deps = [
    "//base",
    "//components/data_sharing/public:features",
  ]
  public_deps = []
}

source_set("prefs") {
  sources = [
    "pref_names.cc",
    "pref_names.h",
  ]
  deps = [
    ":features",
    "//base",
    "//components/pref_registry",
    "//components/prefs",
    "//components/signin/public/base",
    "//components/sync/base",
  ]
  public_deps = []
}

source_set("string_utils") {
  sources = [
    "string_utils.cc",
    "string_utils.h",
  ]
  deps = [
    "//components/strings",
    "//ui/base",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "saved_tab_group_unittest.cc",
    "string_utils_unittest.cc",
    "synthetic_field_trial_helper_unittest.cc",
    "utils_unittest.cc",
  ]
  deps = [
    ":public",
    ":string_utils",
    "//base",
    "//base/test:test_support",
    "//components/optimization_guide/core",
    "//components/pref_registry",
    "//components/prefs:test_support",
    "//components/saved_tab_groups/proto",
    "//components/saved_tab_groups/test_support",
    "//components/sync",
    "//components/sync:test_support",
    "//components/sync_device_info",
    "//components/sync_device_info:test_support",
    "//components/tab_groups",
    "//testing/gmock",
    "//testing/gtest",
    "//url",
  ]
}
