// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=05eb16c7e495a2ae48bdf095b67131f1daf4b4e7$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_VIEWS_TEXTFIELD_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_VIEWS_TEXTFIELD_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/views/cef_textfield.h"
#include "include/capi/views/cef_textfield_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefTextfield_0_CppToC
    : public CefCppToCRefCounted<CefTextfield_0_CppToC, CefTextfield, cef_textfield_0_t> {
 public:
  CefTextfield_0_CppToC();
  virtual ~CefTextfield_0_CppToC();
};

// Wrap a C++ class with a C structure at API version 999999.
// This class may be instantiated and accessed DLL-side only.
class CefTextfield_999999_CppToC
    : public CefCppToCRefCounted<CefTextfield_999999_CppToC, CefTextfield, cef_textfield_999999_t> {
 public:
  CefTextfield_999999_CppToC();
  virtual ~CefTextfield_999999_CppToC();
};

// Helpers to return objects at the globally configured API version.
cef_textfield_0_t* CefTextfieldCppToC_Wrap(CefRefPtr<CefTextfield> c);
CefRefPtr<CefTextfield> CefTextfieldCppToC_Unwrap(cef_textfield_0_t* s);

#endif  // CEF_LIBCEF_DLL_CPPTOC_VIEWS_TEXTFIELD_CPPTOC_H_
