# Copyright 2015 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/config.gni")
import("//build/config/features.gni")
import("//build/config/ui.gni")
import("//media/media_options.gni")
import("//mojo/public/tools/bindings/mojom.gni")
import("//testing/libfuzzer/fuzzer_test.gni")
import("//testing/test.gni")

if (is_apple) {
  import("//build/config/apple/mobile_config.gni")  # For `target_platform`
}

# Common configuration for targets in the media/midi directory.
config("midi_config") {
  if (use_alsa && use_udev) {
    defines = [
      "USE_ALSA",
      "USE_UDEV",
    ]
  }

  visibility = [ ":*" ]
}

component("midi") {
  sources = [
    "message_util.cc",
    "message_util.h",
    "midi_export.h",
    "midi_manager.cc",
    "midi_manager.h",
    "midi_message_queue.cc",
    "midi_message_queue.h",
    "midi_service.cc",
    "midi_service.h",
    "midi_switches.cc",
    "midi_switches.h",
    "task_service.cc",
    "task_service.h",
  ]

  configs += [ ":midi_config" ]

  defines = [ "MIDI_IMPLEMENTATION" ]
  public_deps = [ "//base" ]
  deps = [ ":mojo" ]
  libs = []

  if (is_apple) {
    if (is_ios && target_platform == "tvos") {
      sources += [ "midi_manager_tvos.cc" ]
    } else {
      sources += [
        "midi_manager_mac.cc",
        "midi_manager_mac.h",
      ]
      frameworks = [
        "CoreAudio.framework",
        "CoreFoundation.framework",
        "CoreMIDI.framework",
      ]
    }
  }

  if (use_alsa && use_udev) {
    deps += [ "//crypto" ]
    libs += [ "asound" ]
    sources += [
      "midi_manager_alsa.cc",
      "midi_manager_alsa.h",
    ]
  }

  if (use_udev) {
    deps += [ "//device/udev_linux" ]
  }
}

mojom("mojo") {
  sources = [ "midi_service.mojom" ]

  deps = [ "//mojo/public/mojom/base" ]
}

test("midi_unittests") {
  use_xvfb = use_xvfb_in_this_config

  sources = [
    "message_util_unittest.cc",
    "midi_manager_unittest.cc",
    "midi_message_queue_unittest.cc",
    "task_service_unittest.cc",
  ]

  configs += [ ":midi_config" ]
  deps = [
    ":midi",
    ":mojo",
    "//base/test/:run_all_unittests",
    "//base/test/:test_support",
    "//testing/gtest",
  ]

  if (is_apple && target_platform != "tvos") {
    sources += [ "midi_manager_mac_unittest.cc" ]
    frameworks = [ "CoreMIDI.framework" ]
  }

  if (use_alsa && use_udev) {
    sources += [ "midi_manager_alsa_unittest.cc" ]
  }
}

fuzzer_test("midi_webmidi_data_validator_fuzzer") {
  sources = [ "midi_webmidi_data_validator_fuzzer.cc" ]
  seed_corpus = "fuzz/corpus"
  deps = [ ":midi" ]
}

fuzzer_test("midi_message_queue_fuzzer") {
  sources = [ "midi_message_queue_fuzzer.cc" ]
  seed_corpus = "fuzz/corpus"
  deps = [ ":midi" ]
}
