# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("segmentation_platform") {
  sources = [ "segmentation_platform_service_factory.h" ]
  public_deps = [ "//chrome/browser/profiles:profile" ]
}

static_library("test_utils") {
  testonly = true
  sources = [
    "ukm_data_manager_test_utils.cc",
    "ukm_data_manager_test_utils.h",
  ]
  deps = [
    ":segmentation_platform",
    "//base/test:test_support",
    "//chrome/browser",
    "//chrome/browser/history",
    "//components/segmentation_platform/embedder",
    "//components/segmentation_platform/embedder/default_model:default_model_test_base",
    "//components/segmentation_platform/internal",
    "//components/segmentation_platform/internal:test_support",
    "//components/segmentation_platform/internal/proto",
    "//components/segmentation_platform/public",
    "//components/ukm:test_support",
    "//services/metrics/public/cpp:ukm_builders",
    "//testing/gmock",
  ]
}
